window.NOVAMC_RULES = {
  "version": "2026.01",
  "source": "rules.js",
  "updatedAt": "2026",
  "intro": "Toàn bộ quy định chính thức của NovaMC được tổng hợp đầy đủ theo từng nhóm. Người chơi cần đọc kỹ trước khi tham gia server.",
  "categories": [
    {
      "id": "general",
      "title": "Quy định chung",
      "icon": "📘",
      "summary": "Các thông báo/quy định chung của NovaMC.",
      "lines": [
        "Rule 1: Đang cập nhật",
        "Rule 2: Đang cập nhật"
      ],
      "lineCount": 2
    },
    {
      "id": "pvp",
      "title": "PvP hợp pháp",
      "icon": "⚔️",
      "summary": "Quy định về PvP, đồng ý giao tranh, bằng chứng và xử phạt.",
      "lines": [
        "",
        "📜 QUY ĐỊNH PVP",
        "",
        "",
        "🔹 CHƯƠNG I: QUY ĐỊNH CHUNG 🔹",
        "",
        "",
        "✅ PVP HỢP PHÁP:",
        "  • Phải có sự đồng ý rõ ràng từ CẢ HAI bên trước khi đánh.",
        "  • Các hình thức đồng ý hợp lệ:",
        "    - Chat công khai: yes, ok, đồng ý, pvp, v.v...",
        "    - Video hoặc voice chat có xác nhận đồng ý rõ ràng từ cả hai bên",
        "",
        "❌ CÁC HÀNH VI BỊ NGHIÊM CẤM:",
        "  • PvP bất ngờ, đánh lén, đánh trộm",
        "  • Gài bẫy để ép PvP (trap, lava, TNT, rơi cao, void)",
        "  • Quấy rối PvP sau khi đã từ chối rõ ràng",
        "  • PvP với người đang AFK hoặc không sẵn sàng",
        "",
        "👥 ĐỐI TƯỢNG ÁP DỤNG:",
        "  • Tất cả người chơi trên máy chủ, không phân biệt cấp bậc, thời gian tham gia",
        "",
        "📖 GIẢI THÍCH TỪ NGỮ:",
        "  • PvP: Hành động gây sát thương, tấn công hoặc tiêu diệt người chơi khác bằng công cụ, vũ khí, môi trường hoặc bẫy.",
        "  • PvP tự nguyện: Hình thức PvP trong đó cả hai bên đã bày tỏ sự đồng ý rõ ràng, bằng văn bản (chat) hoặc hành động xác nhận trong game trước khi trận đấu diễn ra.",
        "  • Bằng chứng hợp lệ: Video ghi hình toàn bộ quá trình, ảnh chụp màn hình chat công khai.",
        "",
        "",
        "🔹 CHƯƠNG II: ĐIỀU KIỆN & HÀNH VI BỊ CẤM 🔹",
        "",
        "",
        "📌 ĐIỀU KIỆN BẮT BUỘC TRƯỚC PVP:",
        "  • Phải xác nhận đồng ý qua chat công khai",
        "  • Một lần đồng ý chỉ có hiệu lực cho MỘT trận PvP duy nhất",
        "  • Trận PvP kết thúc khi: một bên chết, bỏ chạy khỏi khu vực chiến đấu, logout, hoặc tuyên bố dừng (stop/end/dừng)",
        "  • Không được tạo sẵn bẫy (hố lava, rơi cao, TNT) rồi mới xin phép PvP",
        "  • Dù đã đồng ý PvP, nếu đối phương không sẵn sàng (đứng yên, AFK, thoát tab), phải dừng lại hoặc hỏi lại",
        "",
        "⚠️ DANH MỤC HÀNH VI BỊ NGHIÊM CẤM (CHI TIẾT):",
        "",
        "  [1] PvP bất ngờ:",
        "    → Tấn công khi chưa có sự đồng ý theo quy định tại Chương II",
        "",
        "  [2] Đánh lén / đánh trộm:",
        "    → Tấn công khi người kia đang AFK.",
        "",
        "  [3] Gài bẫy để ép PvP:",
        "    → Tạo trap, lava, TNT, đẩy xuống void, đẩy rơi cao trước hoặc trong khi PvP mà không được sự đồng ý rõ ràng",
        "",
        "  [4] Quấy rối PvP:",
        "    → Hỏi PvP ≥ 3 lần trong 10 phút sau khi bị từ chối",
        "    → Nhắn tin khiêu khích liên tục để ép PvP",
        "",
        "🔍 GIÁ TRỊ PHÁP LÝ CỦA BẰNG CHỨNG:",
        "  • Video ghi hình: Giá trị cao nhất (phải ghi rõ tên kẻ tấn công, hành vi vi phạm, thời điểm chưa có sự đồng ý). Không chấp nhận video bị cắt ghép.",
        "  • Chat log công khai: Hợp lệ nếu có nội dung đồng ý PvP rõ ràng",
        "  • Chat riêng tư (private message): Không có giá trị trừ khi kèm video ghi toàn màn hình",
        "",
        "",
        "🔹 CHƯƠNG III: BÁO CÁO & XỬ LÝ VI PHẠM 🔹",
        "",
        "",
        "📋 TRÁCH NHIỆM CỦA NGƯỜI CHƠI KHI BỊ PVP TRÁI PHÉP:",
        "",
        "  ✅ Nếu CÓ VIDEO:",
        "     → Gửi trực tiếp cho Admin qua Discord ticket (kênh hỗ trợ)",
        "",
        "  ✅ Nếu KHÔNG CÓ VIDEO:",
        "     → Chấp nhận bị kill",
        "     → Ghi lại ngay: Thời gian (giờ, phút, giây), tọa độ (X, Y, Z), tên người tấn công, hành vi vi phạm cụ thể",
        "     → Gửi báo cáo cho Admin để kiểm tra log máy chủ",
        "     → Admin sẽ đối chiếu log và xử lý nếu log ghi nhận vi phạm rõ ràng",
        "",
        "  ❌ NGHIÊM CẤM:",
        "     → Tự ý trả thù bằng PvP trái phép ngược lại",
        "     → Nếu vi phạm, CẢ HAI bên đều bị xử lý theo quy định",
        "",
        "",
        "⚖️ THẨM QUYỀN & TRÁCH NHIỆM CỦA ADMIN:",
        "",
        "  • Quyền: Từ chối xử lý nếu bằng chứng không rõ ràng, không đúng định dạng",
        "  • Quyền: Ban tạm thời hoặc vĩnh viễn tùy theo mức độ vi phạm",
        "  • Quyền: Điều chỉnh mức phạt khi có tình tiết tăng nặng (tái phạm nhiều lần, gây mất an ninh server)",
        "  • Trách nhiệm: Phản hồi kết quả xử lý trong vòng 48 giờ kể từ khi nhận báo cáo hợp lệ",
        "  • Trách nhiệm: Lưu trữ lịch sử vi phạm của từng người chơi",
        "  • Trách nhiệm: Công bố công khai các vụ việc điển hình để răn đe",
        "",
        "📊 KHUNG XỬ PHẠT (THAM KHẢO):",
        "",
        "  • Lần 1 – vi phạm nhẹ (đánh lén, chưa gây hậu quả lớn):",
        "    → Cảnh cáo + Ban tạm thời 3 ngày",
        "",
        "  • Lần 2 – tái phạm:",
        "    → Ban tạm thời 7 ngày",
        "",
        "  • Lần 3 – tái phạm nhiều, có trap, quấy rối:",
        "    → Ban tạm thời 14 ngày",
        "",
        "  📌 Các trường hợp vi phạm nặng hơn (có thể nhận hình phạt cao hơn khung cơ bản hoặc ban vĩnh viễn ngay lần đầu):",
        "     - Gây mất an ninh server nghiêm trọng",
        "     - Sử dụng bug/exploit để PvP trái phép",
        "",
        "  Ngoài ra, Đội Ngũ ADMIN có quyền điều chỉnh mức phạt linh hoạt dựa trên mức độ nghiêm trọng thực tế của từng vụ việc.",
        "",
        "⚠️ XỬ LÝ KHIẾU NẠI SAI SỰ THẬT:",
        "",
        "  • Người chơi cố tình dựng chuyện, làm giả bằng chứng, báo cáo sai sự thật: xử lý như vi phạm mức độ nghiêm trọng (ban tối thiểu 7 ngày).",
        "  • Nếu hành vi khiếu nại sai sự thật nhằm mục đích hãm hại, đẩy đuổi người chơi khác hoặc gây ảnh hưởng nghiêm trọng đến cộng đồng: ban vĩnh viễn.",
        "",
        "",
        "🔹 CHƯƠNG IV: ĐIỀU KHOẢN THI HÀNH 🔹",
        "",
        "",
        "📅 HIỆU LỰC THI HÀNH:",
        "  • Quy định này có hiệu lực kể từ ngày công bố chính thức trên toàn bộ kênh thông báo của server",
        "  • Trong quá trình thực hiện, nếu có vướng mắc, người chơi phản ánh về Đội Ngũ ADMIN để được hướng dẫn, giải đáp",
        "",
        "✏️ SỬA ĐỔI, BỔ SUNG:",
        "  • Đội Ngũ ADMIN có quyền sửa đổi, bổ sung quy định này khi cần thiết",
        "  • Mọi thay đổi sẽ được thông báo công khai ít nhất 24 giờ trước khi có hiệu lực",
        ""
      ],
      "lineCount": 79
    },
    {
      "id": "hack",
      "title": "Hack / Cheat / X-Ray",
      "icon": "🛑",
      "summary": "Cấm tuyệt đối hack, cheat, x-ray, hacked client và các lợi thế không công bằng.",
      "lines": [
        "",
        "🛑 QUY ĐỊNH HACK / CHEAT / X-RAY",
        "",
        "",
        "🔹 CHƯƠNG I: QUY ĐỊNH CHUNG 🔹",
        "",
        "",
        "❌ CÁC HÀNH VI BỊ NGHIÊM CẤM TUYỆT ĐỐI:",
        "  • X-Ray dưới mọi hình thức (Texture Pack, Resource Pack, Mod)",
        "  • Sử dụng Hacked Client (Wurst, Meteor, Impact, LiquidBounce, Thunder,...)",
        "  • Mod gian lận (ESP, KillAura, AutoMine, Fly, Speed, NoFall, Crits, v.v.)",
        "  • Cài đặt hack/cheat trong máy (kể cả không sử dụng vẫn bị xử phạt)",
        "",
        "✅ MOD ĐƯỢC PHÉP SỬ DỤNG:",
        "  • Chỉ các mod không ảnh hưởng gameplay công bằng",
        "  • Ví dụ: Optifine, Sodium, Litematica, Minimap, vv...",
        "",
        "👥 ĐỐI TƯỢNG ÁP DỤNG:",
        "  • Tất cả người chơi trên máy chủ, không phân biệt cấp bậc",
        "  • Áp dụng cho mọi tài khoản liên quan (Alt Account)",
        "  • Áp dụng cho TẤT CẢ tài khoản có cùng IP (cùng chung địa chỉ mạng)",
        "    → Ví dụ: Người thân trong gia đình, bạn bè cùng nhà, dùng chung WiFi",
        "",
        "📖 GIẢI THÍCH TỪ NGỮ:",
        "  • Hack/Cheat: Phần mềm/mod giúp người chơi có lợi thế bất hợp pháp",
        "  • X-Ray: Nhìn xuyên đất/đá để tìm quặng, rương, công trình ngầm",
        "  • Hacked Client: Client Minecraft tích hợp sẵn các tính năng gian lận",
        "  • Tàng trữ: Có file hack/cheat trong máy tính dù chưa kích hoạt",
        "",
        "",
        "🔹 CHƯƠNG II: CÁC HÀNH VI BỊ CẤM & HÌNH THỨC PHÁT HIỆN 🔹",
        "",
        "",
        "⚠️ DANH MỤC HÀNH VI BỊ NGHIÊM CẤM (CHI TIẾT):",
        "",
        "  [1] X-Ray:",
        "    → Dùng texture pack/resource pack/mod để nhìn xuyên khối",
        "    → Tìm quặng, rương, căn cứ ngầm một cách bất hợp pháp",
        "",
        "  [2] Hacked Client:",
        "    → Sử dụng Wurst, Meteor, Impact, LiquidBounce, Thunder,...",
        "",
        "  [3] ESP:",
        "    → Nhìn xuyên tường thấy vị trí người chơi, quái vật, rương",
        "",
        "  [4] AutoMine / AutoFarm:",
        "    → Tự động đào, tự động farm không cần tương tác",
        "",
        "  [5] Tàng trữ hack/cheat:",
        "    → Có cài đặt file hack trong máy tính dù chưa sử dụng",
        "",
        "🔍 HÌNH THỨC PHÁT HIỆN VI PHẠM:",
        "",
        "  • Phát hiện tự động:",
        "    → Plugin chống hack ghi nhận hành vi bất thường (bay, đi xuyên tường)",
        "    → AntiX-ray ghi nhận đào thẳng tới quặng hiếm",
        "    → Server quét và phát hiện file/client hack trong máy người chơi",
        "    → Hệ thống phát hiện mod/client lạ không được cấp phép khi kết nối",
        "",
        "  • Phát hiện thủ công:",
        "    → Admin/Mod quan sát trực tiếp",
        "    → Người chơi tố giác qua Ticket Discord (kèm video/ảnh)",
        "",
        "  • Kiểm tra đột xuất:",
        "    → Admin yêu cầu share màn hình qua Discord để kiểm tra mod/client",
        "",
        "  • Quét từ xa:",
        "    → Server có cơ chế ghi nhận client hack hoặc file đặc trưng của hacked client",
        "    → Nếu phát hiện client hack trong máy → TỰ ĐỘNG ban vĩnh viễn",
        "    → Không cần hành vi vi phạm trong game, chỉ cần có file là đủ",
        "",
        "📸 GIÁ TRỊ PHÁP LÝ CỦA BẰNG CHỨNG:",
        "  • Video ghi hình: Giá trị cao nhất (không cắt ghép)",
        "  • Ảnh chụp màn hình: Giá trị trung bình (cần kèm log để xác minh)",
        "  • Server log: Giá trị cao (do Admin khai thác)",
        "  • Tố giác không bằng chứng: Kiểm tra thêm, xem xét xử phạt",
        "",
        "",
        "🔹 CHƯƠNG III: XỬ LÝ VI PHẠM & HÌNH PHẠT 🔹",
        "",
        "",
        "⛔ NGUYÊN TẮC XỬ LÝ:",
        "",
        "  • KHÔNG CẢNH BÁO TRƯỚC:",
        "    → Ban vĩnh viễn ngay lập tức đối với tất cả hành vi bị cấm",
        "    → Không giảm án – Không unban dưới mọi hình thức",
        "",
        "  • TỰ NHẬN MÌNH HACK / CHEAT / X-RAY:",
        "    → Bị xử lý ngay lập tức, KHÔNG CẦN LÝ DO",
        "    → Không chấp nhận bất kỳ lời giải thích hay rút lại nào sau đó",
        "    → Dù nói đùa hay không thật vẫn bị xử lý như vi phạm thực tế",
        "",
        "  • CHO MƯỢN ACC VÀ NGƯỜI MƯỢN SỬ DỤNG HACK:",
        "    → CẢ HAI đều bị xử lý (chủ acc + người mượn)",
        "    → Hình phạt: Ban vĩnh viễn ngay lập tức, không ngoại lệ",
        "    → Lý do: Chủ acc chịu trách nhiệm bảo mật tài khoản của mình",
        "    → Không chấp nhận lý do 'bạn mình hack chứ mình không hack'",
        "",
        "  • ÁP DỤNG VỚI MỌI TÀI KHOẢN LIÊN QUAN:",
        "    → Tài khoản chính + tài khoản phụ (Alt Account) đều bị ban vĩnh viễn",
        "    → Cố tình lập tài khoản mới sau khi bị ban → tiếp tục bị ban ngay khi phát hiện",
        "    → Tất cả tài khoản dùng chung IP (cùng địa chỉ mạng)",
        "    → Nếu một tài khoản trong IP bị ban → TOÀN BỘ tài khoản trong IP đó đều bị ban vĩnh viễn",
        "",
        "📊 KHUNG XỬ PHẠT (THAM KHẢO):",
        "",
        "  • Bất kỳ hành vi hack/cheat/x-ray nào:",
        "    → Ban vĩnh viễn NGAY LẬP TỨC",
        "    → Không cảnh báo – Không giảm án – Không unban",
        "",
        "  • Tự nhận mình hack (dù đùa hay thật):",
        "    → Ban vĩnh viễn NGAY LẬP TỨC, không cần lý do",
        "    → Không chấp nhận bất kỳ lời giải thích nào sau đó",
        "",
        "  • Cho mượn acc và người mượn dùng hack:",
        "    → Cả chủ acc và người mượn đều bị ban vĩnh viễn",
        "    → Chủ acc chịu trách nhiệm hoàn toàn về bảo mật tài khoản",
        "",
        "  • Tái phạm sau khi đã bị ban (dùng alt):",
        "    → Ban tiếp tục + IP",
        "",
        "  • Phát tán hack/cheat cho người khác:",
        "    → Ban vĩnh viễn + IP",
        "",
        "⚠️ TÌNH TIẾT TĂNG NẶNG:",
        "  • Sử dụng hack để phá hoại công trình người khác",
        "  • Chia sẻ, phát tán hack/cheat cho người chơi khác",
        "  • Lăng mạ, chống đối Admin khi bị xử lý",
        "    → Có thể bị ban vĩnh viễn kèm chặn IP",
        "",
        "📋 TRÁCH NHIỆM CỦA NGƯỜI CHƠI:",
        "",
        "  ✅ TRƯỚC KHI VÀO SERVER:",
        "     → Vui lòng xóa SẠCH hack, cheat, x-ray, hacked client khỏi máy tính",
        "     → Chỉ sử dụng các mod được phép",
        "",
        "  ✅ TRONG QUÁ TRÌNH CHƠI:",
        "     → Không cài đặt hoặc kích hoạt bất kỳ tính năng gian lận nào",
        "     → Nếu vô tình có file hack, phải xóa NGAY trước khi vào server",
        "",
        "  ✅ KHI PHÁT HIỆN NGƯỜI KHÁC HACK:",
        "     → Ghi hình hoặc chụp màn hình hành vi bất thường",
        "     → Gửi qua Ticket Discord kèm bằng chứng",
        "     → Không tự ý xử lý hay phát ngôn gây war trong chat",
        "",
        "  ✅ BẢO MẬT TÀI KHOẢN:",
        "     → Tuyệt đối không cho mượn acc",
        "     → Nếu cho mượn, bạn tự chịu rủi ro và chịu trách nhiệm hoàn toàn",
        "",
        "⚖️ THẨM QUYỀN & TRÁCH NHIỆM CỦA ADMIN:",
        "",
        "  • Quyền: Ban vĩnh viễn ngay khi phát hiện vi phạm, không cần thông báo trước",
        "  • Quyền: Xử lý người tự nhận hack mà không cần xác minh thêm",
        "  • Quyền: Kiểm tra log, kiểm tra máy người chơi (share màn hình)",
        "  • Quyền: Từ chối khiếu nại, kháng cáo về hack/cheat/x-ray",
        "  • Trách nhiệm: Lưu trữ bằng chứng (log, video) trước khi ban",
        "  • Trách nhiệm: Thông báo lý do ban để răn đe",
        "",
        "",
        "🔹 CHƯƠNG IV: ĐIỀU KHOẢN THI HÀNH 🔹",
        "",
        "",
        "📅 HIỆU LỰC THI HÀNH:",
        "  • Quy định có hiệu lực từ ngày công bố chính thức",
        "  • Không áp dụng hồi tố, trừ khi người chơi tiếp tục tái phạm",
        "",
        "✏️ SỬA ĐỔI, BỔ SUNG:",
        "  • Ban Quản trị có quyền sửa đổi khi cần thiết",
        "  • Thông báo công khai ít nhất 24 giờ trước khi có hiệu lực",
        "",
        "🚫 KHIẾU NẠI & KHÁNG CÁO:",
        "  • Không chấp nhận khiếu nại đối với các trường hợp:",
        "    - Bị ban vì hack/cheat/x-ray",
        "    - Tự nhận mình hack (dù đùa)",
        "    - Cho mượn acc và người mượn dùng hack",
        ""
      ],
      "lineCount": 124
    },
    {
      "id": "phahoai",
      "title": "Phá hoại công trình",
      "icon": "🛡️",
      "summary": "Bảo vệ công trình, farm, thú nuôi và khu vực sinh sống của người chơi.",
      "lines": [
        "",
        "🛡️ QUY ĐỊNH PHÁ HOẠI & TÔN TRỌNG CÔNG TRÌNH",
        "",
        "",
        "🔹 CHƯƠNG I: QUY ĐỊNH CHUNG 🔹",
        "",
        "",
        "❌ CÁC HÀNH VI BỊ NGHIÊM CẤM TUYỆT ĐỐI:",
        "  • Phá, chiếm dụng hoặc chỉnh sửa công trình của người khác khi chưa được phép",
        "  • Đặt / spam block trong hoặc sát công trình người khác nhằm phá, troll hoặc gây khó chịu",
        "  • Phá farm, redstone, máy tự động, cổng Nether / End của người khác",
        "  • Dẫn mob hoặc dùng lava, nước, TNT, piston, redstone để phá hoại gián tiếp",
        "  • Giết mob nuôi / thú cưng của người khác (chó, mèo, ngựa, dân làng, v.v.)",
        "  • Xây công trình phản cảm, che chắn, chặn tầm nhìn, gây lag gần công trình người khác",
        "  • Chiếm đất, bao vây, khóa lối ra vào khiến công trình người khác không thể sử dụng",
        "  • Spam entity gây lag (mob, item, minecart, boat, v.v.) gần khu vực người khác",
        "  • Xây dựng công trình có nội dung nhạy cảm, phản cảm, vi phạm thuần phong mỹ tục",
        "  • Dùng cơ chế game (piston, sticky piston, slime block) để đẩy, di chuyển block trong công trình người khác",
        "  • Thả wither hoặc gọi raid gần công trình của người khác để cố tình phá hoại",
        "  • Sử dụng alt account để phá hoại sau đó chuyển đồ về main để tránh bị phát hiện",
        "",
        "✅ NGUYÊN TẮC TÔN TRỌNG CÔNG TRÌNH:",
        "  • Phải tôn trọng hoàn toàn công trình của người khác, kể cả khi chưa được claim",
        "  • Khi muốn xây dựng gần công trình người khác:",
        "    → BẮT BUỘC phải có sự cho phép của chủ công trình TRƯỚC KHI XÂY",
        "  • Không xây sát quá gần nếu chưa được đồng ý (khoảng cách tối thiểu 100 block)",
        "",
        "👥 ĐỐI TƯỢNG ÁP DỤNG:",
        "  • Tất cả người chơi trên máy chủ, không phân biệt cấp bậc",
        "  • Áp dụng cho mọi tài khoản liên quan (Alt Account)",
        "  • Áp dụng cho TẤT CẢ tài khoản có cùng IP",
        "",
        "📖 GIẢI THÍCH TỪ NGỮ:",
        "  • Công trình: Bất kỳ khối xây dựng nào do người chơi tạo ra (nhà, farm, máy, trang trí, v.v.)",
        "  • Phá hoại: Hành vi phá, sửa, chiếm, làm hỏng công trình của người khác",
        "  • Phá hoại gián tiếp: Dùng mob, lava, nước, TNT, piston để phá mà không trực tiếp đập block",
        "",
        "",
        "🔹 CHƯƠNG II: CÁC HÀNH VI BỊ CẤM & HÌNH THỨC PHÁT HIỆN 🔹",
        "",
        "",
        "⚠️ DANH MỤC HÀNH VI BỊ NGHIÊM CẤM (CHI TIẾT):",
        "",
        "  [1] Phá / chiếm / sửa chữa khi chưa được phép:",
        "    → Phá block, lấy đi nguyên liệu, chiếm nhà, sửa kết cấu",
        "",
        "  [2] Spam block sát công trình:",
        "    → Đặt block phản cảm, spam dày đặc, troll che tầm nhìn",
        "",
        "  [3] Phá farm / máy tự động:",
        "    → Phá hoại redstone, cổng Nether, máy farm, mob grinder",
        "",
        "  [4] Phá hoại gián tiếp:",
        "    → Dẫn creepers, spawn wither, lava, nước, TNT",
        "",
        "  [5] Giết mob nuôi / thú cưng:",
        "    → Giết chó, mèo, ngựa, dân làng, các mob đã thuần hóa hoặc nuôi nhốt",
        "",
        "  [6] Xây dựng phản cảm gây lag:",
        "    → Xây gần người khác mục đích troll, lag hoặc phá",
        "",
        "  [7] Chiếm đất / bao vây:",
        "    → Claim đất bao vây, chặn lối ra vào không cho chủ nhà di chuyển",
        "",
        "  [8] Spam entity gây lag:",
        "    → Spam mob, item, minecart, boat gần khu vực người khác",
        "",
        "  [9] Xây nội dung nhạy cảm, phản cảm:",
        "    → Xây dựng công trình có nội dung xúc phạm, bôi nhọ, vi phạm thuần phong mỹ tục",
        "",
        "  [10] Dùng piston / slime block để phá:",
        "    → Sử dụng cơ chế piston để đẩy, di chuyển block trong khu vực có chủ",
        "",
        "  [11] Thả wither / gọi raid:",
        "    → Cố tình thả wither, gọi raid gần công trình người khác để phá hoại",
        "",
        "  [12] Dùng alt account phá hoại:",
        "    → Sử dụng tài khoản phụ để phá hoại, sau đó chuyển đồ/lợi ích về tài khoản chính",
        "",
        "🔍 HÌNH THỨC PHÁT HIỆN VI PHẠM:",
        "",
        "  • Phát hiện tự động:",
        "    → Log máy chủ ghi nhận block bị phá / đặt",
        "",
        "  • Phát hiện thủ công:",
        "    → Admin/Mod tuần tra kiểm tra",
        "    → Người chơi tố giác qua Ticket Discord (kèm video/ảnh)",
        "",
        "📸 GIÁ TRỊ PHÁP LÝ CỦA BẰNG CHỨNG:",
        "  • Video ghi hình: Giá trị cao nhất",
        "  • Ảnh chụp màn hình: Giá trị trung bình",
        "  • Server log: Giá trị cao (do Admin khai thác)",
        "",
        "",
        "🔹 CHƯƠNG III: XỬ LÝ VI PHẠM & HÌNH PHẠT 🔹",
        "",
        "⛔ NGUYÊN TẮC XỬ LÝ:",
        "",
        "  • Phát hiện phá hoại → Xử lý theo khung phạt chính thức",
        "  • Người chơi cố tình đổ tội cho người khác hoặc dựng chuyện → Xử lý bổ sung",
        "  • Phá hoại và trả thù bằng phá hoại → Cả hai bên đều bị xử lý",
        "",
        "📊 KHUNG XỬ PHẠT (THAM KHẢO):",
        "",
        "  • Lần 1 (vi phạm lần đầu):",
        "    → Ban tạm thời 7 ngày",
        "",
        "  • Lần 2 (tái phạm):",
        "    → Ban tạm thời 14 ngày",
        "",
        "  • Lần 3 (tái phạm nhiều lần):",
        "    → Ban tạm thời 30 ngày",
        "",
        "⚠️ TÌNH TIẾT TĂNG NẶNG (CÓ THỂ BAN NẶNG HƠN HOẶC BAN VĨNH VIỄN):",
        "  • Phá hoại quy mô lớn (cả khu vực, nhiều công trình)",
        "  • Phá hoại có tổ chức (rủ rê nhiều người cùng phá)",
        "  • Phá hoại nghiêm trọng, mất dữ liệu không thể rollback",
        "  • Dùng alt account để phá hoại nhằm trốn tránh trách nhiệm",
        "    → Có thể bị ban vĩnh viễn ngay lần đầu",
        "",
        "  • ÁP DỤNG VỚI MỌI TÀI KHOẢN LIÊN QUAN:",
        "    → Tài khoản chính, tài khoản phụ (Alt Account)",
        "",
        "📋 TRÁCH NHIỆM CỦA NGƯỜI CHƠI:",
        "",
        "  ✅ KHI XÂY GẦN NGƯỜI KHÁC:",
        "     → Bắt buộc hỏi xin phép TRƯỚC",
        "     → Giữ khoảng cách tối thiểu hoặc có ranh giới rõ ràng",
        "",
        "  ✅ KHI BỊ PHÁ HOẠI:",
        "     → Ghi hình ngay lập tức",
        "     → Không tự ý phá lại (sẽ bị xử lý cả hai)",
        "     → Báo cáo qua Ticket Discord kèm bằng chứng",
        "",
        "  ✅ KHI VÔ TÌNH PHÁ HOẠI:",
        "     → Báo Admin ngay, chủ động khắc phục, xin lỗi",
        "     → Có thể giảm nhẹ hình phạt nếu thành khẩn",
        "",
        "⚖️ THẨM QUYỀN & TRÁCH NHIỆM CỦA ADMIN:",
        "",
        "  • Quyền: Rollback công trình bị phá (nếu có backup)",
        "  • Quyền: Điều chỉnh mức phạt linh hoạt theo mức độ",
        "  • Quyền: Xử lý cả chủ công trình nếu cố tình dựng chuyện",
        "  • Trách nhiệm: Phản hồi trong vòng 48 giờ",
        "  • Trách nhiệm: Lưu trữ lịch sử vi phạm",
        "",
        "",
        "🔹 CHƯƠNG IV: ĐIỀU KHOẢN THI HÀNH 🔹",
        "",
        "",
        "📅 HIỆU LỰC THI HÀNH:",
        "  • Quy định có hiệu lực từ ngày công bố chính thức",
        "",
        "✏️ SỬA ĐỔI, BỔ SUNG:",
        "  • Ban Quản trị có quyền sửa đổi khi cần thiết",
        "  • Thông báo công khai ít nhất 24 giờ trước khi có hiệu lực",
        "",
        "🚫 KHIẾU NẠI:",
        "  • Khiếu nại sai sự thật, dựng chuyện để hãm hại người khác: xử lý ban tối thiểu 7 ngày",
        ""
      ],
      "lineCount": 109
    },
    {
      "id": "chat",
      "title": "Cư xử văn minh",
      "icon": "💬",
      "summary": "Quy định về chat, Discord, spam, toxic, quảng cáo và nội dung không phù hợp.",
      "lines": [
        "",
        "💬 QUY ĐỊNH CƯ XỬ VĂN MINH",
        "",
        "",
        "🔹 CHƯƠNG I: QUY ĐỊNH CHUNG 🔹",
        "",
        "",
        "❌ CÁC HÀNH VI BỊ NGHIÊM CẤM TUYỆT ĐỐI:",
        "  • Chửi thề, lăng mạ, xúc phạm người chơi khác dưới mọi hình thức",
        "  • Phân biệt vùng miền, chủng tộc, màu da, tôn giáo, giới tính, xu hướng tính dục",
        "  • Xúc phạm cá nhân hoặc tổ chức (trong game hoặc ngoài đời thực)",
        "  • Khiêu khích, đe dọa, gây hấn, châm biếm, mỉa mai nhằm gây mâu thuẫn",
        "  • Quấy rối, làm phiền, spam tin nhắn người khác trong game hoặc Discord",
        "  • Spam / flood / gửi lặp lại nội dung trong chat (dù chỉ một dòng nhiều lần)",
        "  • Quảng cáo server khác dưới mọi hình thức (tên server, link, IP, Discord)",
        "  • Gửi link lạ, đường dẫn đáng ngờ có nguy cơ lừa đảo, chứa virus/nội dung độc hại",
        "  • Đe dọa DDoS, tấn công, hoặc bất kỳ hành vi nào gây nguy hiểm đến server hoặc người chơi",
        "  • Cố tình gây hiểu lầm, tung tin giả, bịa đặt thông tin sai sự thật về người chơi khác",
        "  • Lợi dụng tên, skin, cape, tên item hoặc bất kỳ nội dung hiển thị nào để xúc phạm",
        "",
        "✅ NGUYÊN TẮC ỨNG XỬ:",
        "  • Đây là chat chung của TẤT CẢ mọi người",
        "  • KHÔNG được phép xúc phạm hoặc toxic, dù có là bạn bè với nhau",
        "  • Hãy giữ thái độ văn minh và tôn trọng người chơi khác",
        "  • Nếu xảy ra tranh chấp, hãy báo Admin thay vì tiếp tục gây hấn",
        "  • Tranh luận là bình thường, nhưng KHÔNG được vượt quá giới hạn xúc phạm",
        "",
        "👥 ĐỐI TƯỢNG ÁP DỤNG:",
        "  • Tất cả người chơi trên máy chủ, không phân biệt cấp bậc",
        "  • Áp dụng trên tất cả các nền tảng: in-game chat, Discord server.",
        "",
        "📖 GIẢI THÍCH TỪ NGỮ:",
        "  • Toxic: Hành vi thái độ tiêu cực, công kích, làm hỏng môi trường chung",
        "  • Spam: Gửi cùng một nội dung nhiều lần trong thời gian ngắn",
        "  • Flood: Gửi quá nhiều dòng tin nhắn liên tiếp gây khó chịu",
        "  • Quấy rối: Hành vi làm phiền, nhắn tin liên tục sau khi đã yêu cầu dừng",
        "",
        "",
        "🔹 CHƯƠNG II: CÁC HÀNH VI BỊ CẤM & HÌNH THỨC PHÁT HIỆN 🔹",
        "",
        "",
        "⚠️ DANH MỤC HÀNH VI BỊ NGHIÊM CẤM (CHI TIẾT):",
        "",
        "  [1] Chửi thề / lăng mạ:",
        "    → Dùng từ ngữ thô tục, xúc phạm trực tiếp hoặc gián tiếp",
        "    → Viết tắt, nói lái, dùng ký tự đặc biệt để chửi cũng bị xử lý",
        "",
        "  [2] Phân biệt / kỳ thị:",
        "    → Phân biệt vùng miền, chủng tộc, màu da, tôn giáo, giới tính",
        "    → Lên án, chế giễu, công kích dựa trên các yếu tố trên",
        "",
        "  [3] Khiêu khích / đe dọa:",
        "    → Nhắn tin khiêu khích, khích bác để người khác phản ứng",
        "    → Đe dọa bạo lực, tấn công, dDoS, hack tài khoản",
        "",
        "  [4] Quấy rối:",
        "    → Nhắn tin riêng nhiều lần sau khi đã bị từ chối",
        "    → Ghép kèo nài ép, mời chơi liên tục gây khó chịu",
        "",
        "  [5] Spam / flood:",
        "    → Gửi tin nhắn lặp lại ≥ 5 lần trong 10 giây",
        "",
        "  [6] Quảng cáo server khác:",
        "    → Gửi tên, IP, Discord, link của server khác",
        "    → Rủ rê người chơi sang server khác dưới mọi hình thức",
        "",
        "  [7] Gửi link độc hại:",
        "    → Link rút gọn không rõ nguồn gốc",
        "    → Link chứa virus, lừa đảo, 18+, auto download",
        "",
        "  [8] Tên / skin phản cảm:",
        "    → Tên nhân vật có nội dung xúc phạm, nhạy cảm, liên quan đến chính trị/giới tính",
        "    → Skin, cape có nội dung 18+, bạo lực, phản động",
        "",
        "🔍 HÌNH THỨC PHÁT HIỆN VI PHẠM:",
        "",
        "  • Phát hiện tự động:",
        "    → Bot Discord tự động filter từ ngữ nhạy cảm",
        "    → Plugin in-game tự động mute khi spam",
        "",
        "  • Phát hiện thủ công:",
        "    → Admin/Mod đọc chat và xử lý",
        "    → Người chơi báo cáo qua Ticket Discord (kèm ảnh/video)",
        "",
        "📸 GIÁ TRỊ PHÁP LÝ CỦA BẰNG CHỨNG:",
        "  • Ảnh chụp màn hình chat: Giá trị cao nhất (không cắt ghép)",
        "  • Server log chat: Giá trị cao (do Admin khai thác)",
        "  • Video ghi hình: Giá trị cao (không cắt ghép)",
        "  • Tố giác không bằng chứng: Kiểm tra thêm, xử phạt nếu có vi phạm",
        "",
        "",
        "🔹 CHƯƠNG III: XỬ LÝ VI PHẠM & HÌNH PHẠT 🔹",
        "",
        "",
        "⛔ NGUYÊN TẮC XỬ LÝ:",
        "",
        "  • Vi phạm lần đầu → xử lý theo khung phạt chính thức",
        "  • Người chơi cố tình khiêu khích để người khác phản ứng → cả hai đều bị xử lý",
        "  • Báo cáo sai sự thật, dựng chuyện hãm hại người khác → xử lý bổ sung",
        "",
        "📊 KHUNG XỬ PHẠT (THAM KHẢO):",
        "",
        "  • Lần 1 (vi phạm lần đầu):",
        "    → Mute 3 ngày (không chat được cả in-game và Discord)",
        "",
        "  • Lần 2 (tái phạm):",
        "    → Ban 1 Ngày + Mute 7 ngày",
        "",
        "  • Lần 3 (tái phạm nhiều lần):",
        "    → Ban 3 ngày + Mute 14 ngày",
        "",
        "⚠️ TÌNH TIẾT TĂNG NẶNG (CÓ THỂ BAN NẶNG HƠN HOẶC BAN VĨNH VIỄN):",
        "  • Xúc phạm nghiêm trọng (liên quan đến gia đình, người thân, tổn thương tinh thần)",
        "  • Quấy rối nhiều lần, liên tục, gây áp lực tâm lý",
        "  • Đe dọa tấn công, dDoS, hack tài khoản",
        "  • Phát tán thông tin cá nhân (doxxing) của người chơi khác",
        "    → Có thể bị ban vĩnh viễn ngay lần đầu",
        "",
        "📋 TRÁCH NHIỆM CỦA NGƯỜI CHƠI:",
        "",
        "  ✅ KHI TRANH CHẤP XẢY RA:",
        "     → Dừng ngay, không tiếp tục gây hấn",
        "     → Chụp ảnh màn hình chat để lưu bằng chứng",
        "     → Báo Admin qua Ticket Discord",
        "",
        "  ✅ KHI BỊ XÚC PHẠM:",
        "     → Không chửi lại (sẽ bị xử lý cả hai)",
        "     → Ghi lại bằng chứng, gửi báo cáo",
        "",
        "  ✅ KHI VÔ TÌNH VI PHẠM:",
        "     → Xin lỗi công khai, rút lại lời nói",
        "     → Có thể giảm nhẹ hình phạt nếu thành khẩn",
        "",
        "⚖️ THẨM QUYỀN & TRÁCH NHIỆM CỦA ADMIN:",
        "",
        "  • Quyền: Mute, ban tạm thời, ban vĩnh viễn tùy mức độ",
        "  • Quyền: Xem toàn bộ chat log (kể cả tin nhắn đã xóa)",
        "  • Quyền: Từ chối xử lý nếu bằng chứng không rõ ràng",
        "  • Trách nhiệm: Phản hồi trong vòng 24 giờ đối với vi phạm chat",
        "  • Trách nhiệm: Lưu trữ lịch sử vi phạm",
        "",
        "",
        "🔹 CHƯƠNG IV: ĐIỀU KHOẢN THI HÀNH 🔹",
        "",
        "",
        "📅 HIỆU LỰC THI HÀNH:",
        "  • Quy định có hiệu lực từ ngày công bố chính thức",
        "",
        "✏️ SỬA ĐỔI, BỔ SUNG:",
        "  • Ban Quản trị có quyền sửa đổi khi cần thiết",
        "  • Thông báo công khai ít nhất 24 giờ trước khi có hiệu lực",
        "",
        "🚫 KHIẾU NẠI:",
        "  • Khiếu nại sai sự thật, dựng chuyện để hãm hại người khác: xử lý ban tối thiểu 7 ngày",
        ""
      ],
      "lineCount": 108
    },
    {
      "id": "quayroi",
      "title": "Quấy rối & xâm phạm base",
      "icon": "🏠",
      "summary": "Cấm làm phiền, bám đuôi, spam hành động và xâm phạm base người khác.",
      "lines": [
        "",
        "🛑 QUY ĐỊNH QUẤY RỐI & XÂM PHẠM BASE",
        "",
        "",
        "🔹 CHƯƠNG I: QUY ĐỊNH CHUNG 🔹",
        "",
        "",
        "❌ CÁC HÀNH VI QUẤY RỐI & LÀM PHIỀN BỊ NGHIÊM CẤM:",
        "  • Spam chat, spam lệnh gây khó chịu, làm loạn chat",
        "  • Theo đuôi, bám đuổi, làm phiền người chơi khác khi họ đã từ chối rõ ràng",
        "  • Khiêu khích, trêu chọc quá mức, cố tình gây ức chế, chọc tức người khác",
        "  • Cố ý cản trở gameplay của người khác (đẩy ngã, chặn đường, cản trở di chuyển, phá nhịp chơi)",
        "  • Tiếp tục làm phiền sau khi đã được người khác nhắc nhở hoặc cảnh cáo bởi ADMIN",
        "  • Spam âm thanh, hành động (crouch spam, hit spam, v.v.) gần người chơi khác",
        "  • Lợi dụng cơ chế game (piston, đẩy, kéo) để làm phiền người chơi khác",
        "",
        "",
        "🏠 XÂM PHẠM BASE / KHU VỰC SINH SỐNG:",
        "",
        "  ❌ Không được tự ý vào base hoặc khu vực sinh sống của người khác để thực hiện các hành vi sau:",
        "",
        "  • Làm phiền, quấy rối hoặc gây khó chịu dưới mọi hình thức",
        "  • Cản trở hoạt động chính đáng (xây dựng, farm, AFK, PvE, build, thiết kế, v.v.)",
        "  • Spam hành động tại base của người khác (crouch spam, hit spam, đặt block rồi phá)",
        "  • Xây dựng công trình sát nách base người khác (dù chưa claim) gây mất mỹ quan và không gian riêng",
        "",
        "✅ NGUYÊN TẮC TÔN TRỌNG BASE:",
        "  • Nếu không được mời hoặc không có lý do chính đáng, KHÔNG được tự ý vào base người khác phá",
        "  • Khi được yêu cầu rời khỏi base, phải rời đi NGAY LẬP TỨC",
        "",
        "",
        "👥 ĐỐI TƯỢNG ÁP DỤNG:",
        "  • Tất cả người chơi trên máy chủ, không phân biệt cấp bậc",
        "",
        "📖 GIẢI THÍCH TỪ NGỮ:",
        "  • Base: Khu vực sinh sống, xây dựng, sinh hoạt chính của người chơi (nhà, đất claim, khu vực rào chắn)",
        "  • Quấy rối: Hành vi làm phiền, gây khó chịu, ảnh hưởng đến trải nghiệm người chơi khác",
        "  • Spam hành động: Lặp đi lặp lại một hành động (crouch, nhảy, đập tay, v.v.) gây khó chịu",
        "",
        "",
        "🔹 CHƯƠNG II: CÁC HÀNH VI BỊ CẤM & HÌNH THỨC PHÁT HIỆN 🔹",
        "",
        "",
        "⚠️ DANH MỤC HÀNH VI BỊ NGHIÊM CẤM (CHI TIẾT):",
        "",
        "  [1] Spam chat / DM / lệnh:",
        "    → Gửi tin nhắn lặp lại ≥5 lần trong 30 giây",
        "    → Spam lệnh /tpa, /tpahere, /msg liên tục gây khó chịu",
        "",
        "  [2] Theo đuôi làm phiền:",
        "    → Bám theo người chơi khác khi họ đã yêu cầu dừng",
        "    → Nhảy nhót, spam hành động quanh người chơi",
        "",
        "  [3] Khiêu khích / gây ức chế:",
        "    → Nói những câu có tính chất châm chọc, mỉa mai, xúc xiểm",
        "    → Cố tình làm hành động phá nhịp chơi (phá block người khác đang đặt)",
        "",
        "  [4] Cản trở gameplay:",
        "    → Đẩy ngã, chặn đường, đứng chặn cầu thang, cửa",
        "    → Phá nhịp đào, xây của người khác bằng cách đặt block trước mặt",
        "",
        "  [5] Đứng lì trong base:",
        "    → Đứng yên trong base người khác dù đã được yêu cầu rời đi",
        "    → AFK trong base người khác gây chiếm chỗ, khó chịu",
        "",
        "  [6] Spam hành động trong base:",
        "    → Crouch spam, hit spam, đặt block rồi phá ngay trong khuôn viên base",
        "",
        "🔍 HÌNH THỨC PHÁT HIỆN VI PHẠM:",
        "",
        "  • Phát hiện tự động:",
        "    → Bot/Plugin ghi nhận spam chat, spam lệnh → tự động mute/kick",
        "",
        "  • Phát hiện thủ công:",
        "    → ADMIN/Mod tuần tra kiểm tra",
        "    → Người chơi tố giác qua Ticket Discord (kèm video/ảnh)",
        "",
        "📸 GIÁ TRỊ PHÁP LÝ CỦA BẰNG CHỨNG:",
        "  • Video ghi hình: Giá trị cao nhất (không cắt ghép)",
        "  • Ảnh chụp màn hình: Giá trị trung bình (cần kèm log)",
        "",
        "",
        "🔹 CHƯƠNG III: XỬ LÝ VI PHẠM & HÌNH PHẠT 🔹",
        "",
        "",
        "⛔ NGUYÊN TẮC XỬ LÝ:",
        "",
        "  • Phát hiện quấy rối / xâm phạm base → xử lý theo khung phạt chính thức",
        "  • Người chơi cố tình khiêu khích để người khác phản ứng → cả hai đều bị xử lý",
        "  • Báo cáo sai sự thật, dựng chuyện để trả thù → xử lý bổ sung",
        "",
        "📊 KHUNG XỬ PHẠT (THAM KHẢO):",
        "",
        "  • Lần 1 (vi phạm lần đầu):",
        "    → Ban tạm thời 3 ngày",
        "",
        "  • Lần 2 (tái phạm):",
        "    → Ban tạm thời 7 ngày",
        "",
        "  • Lần 3 (tái phạm nhiều lần):",
        "    → Ban tạm thời 14 ngày",
        "",
        "⚠️ TÌNH TIẾT TĂNG NẶNG (CÓ THỂ BAN NẶNG HƠN HOẶC BAN VĨNH VIỄN):",
        "  • Quấy rối nghiêm trọng, nhiều lần trong thời gian ngắn",
        "  • Xâm phạm base có chứa tài sản lớn, vật phẩm quý hiếm",
        "  • Phối hợp nhiều người cùng quấy rối / xâm phạm base",
        "  • Sử dụng alt account để quấy rối sau khi đã bị ban main",
        "    → Có thể bị ban vĩnh viễn ngay lần đầu",
        "",
        "📋 TRÁCH NHIỆM CỦA NGƯỜI CHƠI:",
        "",
        "  ✅ KHI BỊ QUẤY RỐI:",
        "     → Chụp ảnh / quay video hành vi vi phạm",
        "     → Không chửi lại, không gây hấn ngược",
        "     → Gửi báo cáo qua Ticket Discord cho ADMIN",
        "",
        "  ✅ KHI CÓ NGƯỜI VÀO BASE TRÁI PHÉP:",
        "     → Yêu cầu họ rời đi bằng chat công khai (để lưu bằng chứng)",
        "     → Nếu không chịu rời, ghi hình và báo ADMIN",
        "",
        "  ✅ KHI VÔ TÌNH QUẤY RỐI NGƯỜI KHÁC:",
        "     → Rời đi ngay lập tức",
        "     → Xin lỗi để tránh hiểu lầm",
        "",
        "⚖️ THẨM QUYỀN & TRÁCH NHIỆM CỦA ADMIN:",
        "",
        "  • Quyền: Teleport đến kiểm tra base khi nhận được báo cáo",
        "  • Quyền: Điều chỉnh mức phạt linh hoạt theo mức độ",
        "  • Trách nhiệm: Phản hồi trong vòng 24 giờ với các trường hợp quấy rối cấp bách",
        "  • Trách nhiệm: Lưu trữ lịch sử vi phạm",
        "",
        "",
        "🔹 CHƯƠNG IV: ĐIỀU KHOẢN THI HÀNH 🔹",
        "",
        "",
        "📅 HIỆU LỰC THI HÀNH:",
        "  • Quy định có hiệu lực từ ngày công bố chính thức",
        "",
        "✏️ SỬA ĐỔI, BỔ SUNG:",
        "  • Đội Ngũ ADMIN có quyền sửa đổi khi cần thiết",
        "  • Thông báo công khai ít nhất 24 giờ trước khi có hiệu lực",
        "",
        "🚫 KHIẾU NẠI:",
        "  • Khiếu nại sai sự thật, dựng chuyện để hãm hại người khác: xử lý ban tối thiểu 7 ngày",
        ""
      ],
      "lineCount": 95
    },
    {
      "id": "claim",
      "title": "Claim & chiếm đất",
      "icon": "🏷️",
      "summary": "Nguyên tắc claim đất hợp lệ, khoảng cách claim và xử lý chiếm đất trái phép.",
      "lines": [
        "",
        "🏷️ QUY ĐỊNH CLAIM",
        "",
        "",
        "🔹 CHƯƠNG I: QUY ĐỊNH CHUNG 🔹",
        "",
        "",
        "❌ CÁC HÀNH VI CLAIM & CHIẾM ĐẤT TRÁI PHÉP BỊ NGHIÊM CẤM:",
        "  • Claim trên khu vực đã có công trình dù chưa hoàn thiện",
        "  • Claim trên khu vực đã được san phẳng / dọn dẹp để chuẩn bị xây dựng",
        "  • Claim giữ chỗ rồi không xây dựng trong thời gian dài",
        "  • Claim quá to chiếm dụng đất nhưng không xây gì trong thời gian dài",
        "  • Spam claim nhỏ hoặc claim gây ảnh hưởng xấu đến khu vực xung quanh",
        "  • Gỡ block, phá dấu hiệu hoạt động của người khác rồi claim",
        "  • Claim đè lên khu vực có dấu hiệu hoạt động của người khác:",
        "  Các dấu hiệu hoạt động bao gồm nhưng không giới hạn:",
        "    → Rương, lò nung, bàn chế tạo, anvil, đe, furnace, blast furnace",
        "    → Block đánh dấu (biển bảng, khung tranh, đầu mob, v.v.)",
        "    → Ruộng lúa, cà rốt, khoai tây, nông sản đã trồng",
        "    → Farm tạm thời (động vật, quái vật, thực phẩm)",
        "    → Khu vực đã được san ủi, phẳng mặt bằng",
        "    → Cột đá, đuốc, cột mốc đánh dấu ranh giới",
        "    → Hệ thống đường đi, lối mòn nhân tạo",
        "",
        "🟡 Mọi hành vi trên đều bị xem là CƯỚP ĐẤT / CHIẾM DỤNG ĐẤT TRÁI PHÉP",
        "",
        "",
        "✅ NGUYÊN TẮC CLAIM ĐẤT HỢP LỆ:",
        "",
        "  • Chỉ được phép claim khu vực đã xây dựng, hoặc đang chuẩn bị xây dựng (có nguyên liệu, có dấu hiệu rõ ràng)",
        "  • Không claim quá to chiếm dụng đất rồi bỏ không (khoảng trống lớn hơn 2 lần diện tích xây dựng)",
        "  • Tôn trọng hoàn toàn công trình và khu vực đã có người sử dụng, KỂ CẢ KHI CHƯA CLAIM",
        "  • Khi muốn claim gần khu vực có người ở hoặc gần claim của người khác:",
        "    → BẮT BUỘC phải xin phép và được sự đồng ý rõ ràng TRƯỚC",
        "  • Không được lợi dụng việc chưa claim của người khác để chiếm đất",
        "  • Khoảng cách tối thiểu giữa các claim: 50 block (trừ khi được cho phép)",
        "",
        "  🔹 Claim hợp lệ là claim có:",
        "    → Công trình đã được xây dựng (nhà, tường, mái, cửa, v.v.)",
        "    → Hoặc đang trong quá trình xây dựng (có nguyên vật liệu, khung sườn)",
        "    → Hoặc có dấu hiệu rõ ràng về kế hoạch xây dựng (biển báo, cọc mốc, v.v.)",
        "",
        "",
        "👥 ĐỐI TƯỢNG ÁP DỤNG:",
        "  • Tất cả người chơi trên máy chủ, không phân biệt cấp bậc",
        "",
        "📖 GIẢI THÍCH TỪ NGỮ:",
        "  • Claim: Hành động chiếm giữ khu đất bằng plugin claim (hoặc tự đánh dấu khu vực)",
        "  • Giữ chỗ: Claim đất nhưng không sử dụng trong thời gian dài",
        "  • Dấu hiệu hoạt động: Bất kỳ thứ gì chứng tỏ người chơi đã/đang sử dụng khu vực đó",
        "",
        "",
        "🔹 CHƯƠNG II: CÁC HÀNH VI BỊ CẤM & HÌNH THỨC PHÁT HIỆN 🔹",
        "",
        "",
        "⚠️ DANH MỤC HÀNH VI BỊ NGHIÊM CẤM (CHI TIẾT):",
        "",
        "  [1] Claim trên công trình đang có chủ:",
        "    → Claim lên nhà, tường, farm, máy móc đã được xây dựng trước đó",
        "    → Claim lên khu vực đã có biển báo, cột mốc, rào chắn sơ bộ",
        "",
        "  [2] Claim giữ chỗ:",
        "    → Claim đất nhưng sau 7 ngày vẫn chưa xây dựng bất cứ thứ gì",
        "    → Claim khu vực quá lớn so với nhu cầu thực tế",
        "",
        "  [3] Spam claim gây ảnh hưởng:",
        "    → Tạo quá nhiều claim nhỏ lẻ chi chít gây khó chịu",
        "    → Claim bao vây, cắt đường đi của người khác",
        "",
        "  [4] Gỡ dấu hiệu hoạt động rồi claim:",
        "    → Phá rương, lò, biển bảng, đuốc của người khác để chiếm đất",
        "",
        "  [5] Claim đè lên khu vực có dấu hiệu hoạt động:",
        "    → Claim lên ruộng đã cày, nông sản đã trồng",
        "    → Claim lên đường hầm, mỏ đang khai thác",
        "",
        "  [6] Claim sát nút không xin phép:",
        "    → Claim cách claim người khác dưới 50 block mà không xin phép",
        "",
        "  [7] Lợi dụng chưa claim để chiếm đất:",
        "    → Thấy khu vực chưa claim nhưng có dấu hiệu hoạt động → vẫn claim",
        "    → Chủ công trình chưa kịp claim → đến claim trước",
        "",
        "🔍 HÌNH THỨC PHÁT HIỆN VI PHẠM:",
        "",
        "  • Phát hiện tự động:",
        "    → Log ghi nhận hành vi gỡ block / đặt block",
        "",
        "  • Phát hiện thủ công:",
        "    → ADMIN/Mod tuần tra kiểm tra khu vực",
        "    → Người chơi tố giác qua Ticket Discord (kèm ảnh/video)",
        "",
        "📸 GIÁ TRỊ PHÁP LÝ CỦA BẰNG CHỨNG:",
        "  • Video ghi hình: Giá trị cao nhất (không cắt ghép)",
        "  • Ảnh chụp màn hình trước/sau: Giá trị trung bình (cần kèm log)",
        "  • Server log: Giá trị cao (do ADMIN khai thác)",
        "",
        "",
        "🔹 CHƯƠNG III: XỬ LÝ VI PHẠM & HÌNH PHẠT 🔹",
        "",
        "",
        "⛔ NGUYÊN TẮC XỬ LÝ:",
        "",
        "  • Phát hiện claim trái phép → xử lý theo khung phạt chính thức",
        "  • Claim vi phạm sẽ bị xóa ngay lập tức",
        "  • Tài sản trong claim vi phạm có thể bị mất vĩnh viễn",
        "",
        "📊 KHUNG XỬ PHẠT (THAM KHẢO):",
        "",
        "  • Lần 1 (vi phạm lần đầu):",
        "    → Cảnh báo bằng văn bản",
        "    → Xóa toàn bộ claim vi phạm (mất tài sản)",
        "",
        "  • Lần 2 (tái phạm):",
        "    → Ban tạm thời 7 ngày",
        "    → Xóa claim vi phạm",
        "",
        "  • Lần 3 (tái phạm nhiều lần hoặc cố tình):",
        "    → Ban tạm thời 14 ngày",
        "    → Xóa claim vi phạm",
        "",
        "⚠️ TÌNH TIẾT TĂNG NẶNG (CÓ THỂ BAN NẶNG HƠN HOẶC BAN VĨNH VIỄN):",
        "  • Chiếm đất có tổ chức, claim tràn lan",
        "  • Claim đè lên công trình lớn, giá trị cao",
        "  • Cố tình claim gây chiến tranh đất đai",
        "  • Sử dụng alt account để claim tránh bị phát hiện",
        "    → Có thể bị ban vĩnh viễn ngay lần đầu",
        "",
        "📋 TRÁCH NHIỆM CỦA NGƯỜI CHƠI:",
        "",
        "  ✅ KHI CHUẨN BỊ CLAIM ĐẤT:",
        "     → Kiểm tra khu vực có dấu hiệu hoạt động của người khác không",
        "     → Nếu có, bỏ qua, tìm khu vực khác",
        "     → Nếu muốn claim gần người khác, phải xin phép TRƯỚC",
        "",
        "  ✅ KHI BỊ CLAIM CHIẾM ĐẤT:",
        "     → Ghi hình, chụp ảnh toàn bộ khu vực",
        "     → Ghi lại tọa độ, thời gian, tên người claim",
        "     → Báo cáo qua Ticket Discord",
        "",
        "  ✅ KHI VÔ TÌNH CLAIM TRÚNG KHU VỰC CÓ DẤU HIỆU:",
        "     → Bỏ claim ngay lập tức",
        "     → Xin lỗi chủ khu vực (qua chat công khai hoặc DM)",
        "     → Xin phép chủ khu vực được claim gần (nếu có nhu cầu)",
        "     → Báo ADMIN để được hướng dẫn (nếu cần)",
        "     → Nếu thành khẩn, xin lỗi và khắc phục, có thể giảm nhẹ hình phạt",
        "",
        "⚖️ THẨM QUYỀN & TRÁCH NHIỆM CỦA ADMIN:",
        "",
        "  • Quyền: Xóa claim vi phạm bất kỳ lúc nào",
        "  • Quyền: Xem lịch sử claim của người chơi",
        "  • Quyền: Điều chỉnh mức phạt linh hoạt theo mức độ",
        "  • Trách nhiệm: Phản hồi trong vòng 24 giờ",
        "  • Trách nhiệm: Lưu trữ lịch sử vi phạm claim",
        "",
        "",
        "🔹 CHƯƠNG IV: ĐIỀU KHOẢN THI HÀNH 🔹",
        "",
        "",
        "📅 HIỆU LỰC THI HÀNH:",
        "  • Quy định có hiệu lực từ ngày công bố chính thức",
        "",
        "✏️ SỬA ĐỔI, BỔ SUNG:",
        "  • Đội Ngũ ADMIN có quyền sửa đổi khi cần thiết",
        "  • Thông báo công khai ít nhất 24 giờ trước khi có hiệu lực",
        "",
        "🚫 KHIẾU NẠI:",
        "  • Khiếu nại sai sự thật, dựng chuyện để hãm hại người khác: xử lý ban tối thiểu 7 ngày",
        ""
      ],
      "lineCount": 118
    },
    {
      "id": "scam",
      "title": "Lừa đảo / Scam",
      "icon": "⚠️",
      "summary": "Cấm lừa đảo giao dịch, dịch vụ, mượn đồ không trả và dùng alt để scam.",
      "lines": [
        "",
        "⚠️ LỪA ĐẢO / SCAM",
        "",
        "",
        "🔹 CHƯƠNG I: QUY ĐỊNH CHUNG 🔹",
        "",
        "",
        "❌ CÁC HÀNH VI LỪA ĐẢO BỊ NGHIÊM CẤM TUYỆT ĐỐI:",
        "  • Lừa đảo trong mua bán vật phẩm hoặc dịch vụ trong server",
        "  • Nhận tiền / vật phẩm nhưng không giao đúng - đủ - như đã thỏa thuận",
        "  • Đánh tráo vật phẩm (đổi item kém chất lượng)",
        "  • Gian dối về thông tin vật phẩm (số lượng, cấp độ, enchant, độ hiếm, nguồn gốc, v.v.)",
        "  • Giao dịch mập mờ, cố tình không nói rõ điều kiện, lợi dụng sự thiếu hiểu biết",
        "  • Dùng alt account để scam hoặc tẩu tán tài sản sang tài khoản khác",
        "  • Hứa hẹn dịch vụ (build, farm, đào mỏ, v.v.) nhận tiền trước nhưng không làm",
        "  • Mượn đồ không trả, mượn rồi logout/biến mất",
        "  • Lợi dụng niềm tin để chiếm đoạt vật phẩm có giá trị cao",
        "",
        "",
        "✅ NGUYÊN TẮC GIAO DỊCH AN TOÀN:",
        "",
        "  • Khuyến khích giao dịch rõ ràng qua chat công khai hoặc ghi hình (record) toàn bộ quá trình",
        "  • Giao dịch giá trị lớn nên nhờ ADMIN làm trung gian để đảm bảo an toàn",
        "  • Lưu lại toàn bộ chat thỏa thuận (chụp màn hình hoặc copy log)",
        "  • Không giao dịch với người chơi có tiền sử scam hoặc không rõ danh tính",
        "  • Khi giao dịch bằng vật phẩm đổi vật phẩm, nên ghi rõ số lượng, chất lượng, enchant trong chat",
        "",
        "🔹 ADMIN chỉ xử lý khi có bằng chứng rõ ràng (chat log, video, hoặc ảnh chụp màn hình)",
        "",
        "",
        "👥 ĐỐI TƯỢNG ÁP DỤNG:",
        "  • Tất cả người chơi trên máy chủ, không phân biệt cấp bậc",
        "",
        "📖 GIẢI THÍCH TỪ NGỮ:",
        "  • Scam: Hành vi lừa đảo, gian lận trong giao dịch để chiếm đoạt tài sản",
        "  • Đánh tráo: Đưa vật phẩm khác với thỏa thuận ban đầu",
        "  • Giao dịch mập mờ: Cố tình không nói rõ thông tin, lợi dụng kẽ hở",
        "",
        "",
        "🔹 CHƯƠNG II: CÁC HÀNH VI BỊ CẤM & HÌNH THỨC PHÁT HIỆN 🔹",
        "",
        "",
        "⚠️ DANH MỤC HÀNH VI BỊ NGHIÊM CẤM (CHI TIẾT):",
        "",
        "  [1] Nhận tiền/vật phẩm không giao hàng:",
        "    → Thỏa thuận giá 10 kim cương, nhận rồi không đưa đồ",
        "    → Nhận tiền trước rồi logout, tránh mặt, đổi tên",
        "",
        "  [2] Đánh tráo vật phẩm:",
        "    → Thỏa thuận bán netherite sword enchant, giao iron sword",
        "    → Enchant giả (mượn tạm, không phải của mình)",
        "",
        "  [3] Gian dối thông tin:",
        "    → Bảo item có enchant Sharpness V nhưng thực tế chỉ có Sharpness III",
        "    → Nói dối về số lượng, nguồn gốc, xuất xứ",
        "",
        "  [4] Giao dịch mập mờ:",
        "    → Cố tình nói mập mờ, sau đó hiểu theo hướng có lợi cho mình",
        "    → Không nói rõ item kèm theo",
        "",
        "  [5] Dùng alt account để scam:",
        "    → Tạo tài khoản phụ để lừa đảo, sau đó chuyển đồ về main",
        "    → Dùng alt để tránh bị phát hiện danh tính thật",
        "",
        "  [6] Mượn đồ không trả:",
        "    → Mượn đồ để dùng thử nhưng không trả",
        "    → Hứa trả sau nhưng biến mất, cắt liên lạc",
        "",
        "  [7] Lừa đảo dịch vụ:",
        "    → Nhận tiền xây nhà nhưng xây dở dang, sai yêu cầu",
        "    → Nhận tiền đào mỏ nhưng chỉ đào qua loa rồi bỏ",
        "",
        "🔍 HÌNH THỨC PHÁT HIỆN VI PHẠM:",
        "",
        "  • Phát hiện qua báo cáo:",
        "    → Người bị hại gửi Ticket kèm ảnh/video/chat log",
        "    → ADMIN sẽ yêu cầu bên kia cung cấp bằng chứng",
        "",
        "  • Phát hiện qua log:",
        "    → ADMIN kiểm tra log giao dịch (nếu có plugin)",
        "    → Kiểm tra log chat để đối chiếu thỏa thuận",
        "",
        "📸 GIÁ TRỊ PHÁP LÝ CỦA BẰNG CHỨNG:",
        "",
        "  • Chat log công khai: Giá trị cao nhất (rõ ràng thỏa thuận)",
        "  • Video ghi hình: Giá trị cao nhất (không cắt ghép)",
        "  • Ảnh chụp màn hình chat: Giá trị trung bình",
        "  • Chat riêng tư (DM): Giá trị thấp (dễ giả mạo, cần video hoặc log từ Discord)",
        "",
        "",
        "🔹 CHƯƠNG III: XỬ LÝ VI PHẠM & HÌNH PHẠT 🔹",
        "",
        "",
        "⛔ NGUYÊN TẮC XỬ LÝ:",
        "",
        "  • Phát hiện scam → xử lý theo khung phạt chính thức",
        "  • Tài sản bị scam (nếu xác định rõ ràng) sẽ được hoàn trả nếu còn trong log",
        "  • Người bị hại cố tình dựng chuyện → xử lý ngược lại",
        "  • Giao dịch bằng miệng, không có bằng chứng → ADMIN có quyền từ chối xử lý",
        "",
        "📊 KHUNG XỬ PHẠT (THAM KHẢO):",
        "",
        "  • Lần 1 (vi phạm lần đầu):",
        "    → Ban tạm thời 3 ngày",
        "    → Tịch thu toàn bộ tài sản có liên quan đến scam",
        "",
        "  • Lần 2 (tái phạm):",
        "    → Ban tạm thời 7 ngày",
        "    → Tịch thu tài sản và phạt thêm 50% giá trị vụ scam",
        "",
        "  • Lần 3 (tái phạm nhiều lần hoặc cố tình):",
        "    → Ban tạm thời 14 ngày",
        "    → Tịch thu toàn bộ tài sản trong acc",
        "    → Tịch thu tài sản và phạt thêm x2 giá trị vụ scam",
        "",
        "⚠️ TÌNH TIẾT TĂNG NẶNG (CÓ THỂ BAN NẶNG HƠN HOẶC BAN VĨNH VIỄN):",
        "  • Scam giá trị lớn",
        "  • Scam có tổ chức (nhiều người cùng lừa đảo)",
        "  • Scam nhiều nạn nhân cùng lúc",
        "  • Sử dụng alt account để tẩu tán tài sản",
        "  • Scam dưới mọi hình thức và không chịu trả lại",
        "    → Có thể bị ban vĩnh viễn ngay lần đầu",
        "",
        "  • ÁP DỤNG VỚI MỌI TÀI KHOẢN LIÊN QUAN:",
        "    → Tài khoản chính, tài khoản phụ (Alt Account)",
        "",
        "📋 TRÁCH NHIỆM CỦA NGƯỜI CHƠI:",
        "",
        "  ✅ TRƯỚC KHI GIAO DỊCH:",
        "     → Thỏa thuận rõ ràng bằng chat công khai",
        "     → Ghi hình toàn bộ quá trình giao dịch",
        "     → Giao dịch giá trị lớn → nhờ ADMIN làm trung gian",
        "",
        "  ✅ KHI BỊ SCAM:",
        "     → Lưu lại toàn bộ chat, ảnh chụp, video",
        "     → Gửi báo cáo qua Ticket Discord ngay lập tức",
        "     → Không chửi bới, đe dọa người đã scam",
        "",
        "  ✅ KHI VÔ TÌNH SCAM (hiểu lầm, giao nhầm):",
        "     → Chủ động trả lại vật phẩm ngay",
        "     → Xin lỗi người bị hại",
        "     → Báo ADMIN để xác nhận đã giải quyết",
        "     → Nếu thành khẩn, có thể bỏ qua hoặc giảm nhẹ hình phạt",
        "",
        "⚖️ THẨM QUYỀN & TRÁCH NHIỆM CỦA ADMIN:",
        "",
        "  • Quyền: Tịch thu tài sản có nguồn gốc từ scam",
        "  • Quyền: Ban tạm thời, vĩnh viễn tùy mức độ",
        "  • Quyền: Từ chối xử lý nếu không đủ bằng chứng",
        "  • Trách nhiệm: Phản hồi trong vòng 24-48 giờ",
        "  • Trách nhiệm: Lưu trữ lịch sử vi phạm scam",
        "",
        "",
        "🔹 CHƯƠNG IV: ĐIỀU KHOẢN THI HÀNH 🔹",
        "",
        "",
        "📅 HIỆU LỰC THI HÀNH:",
        "  • Quy định có hiệu lực từ ngày công bố chính thức",
        "",
        "✏️ SỬA ĐỔI, BỔ SUNG:",
        "  • Đội Ngũ ADMIN có quyền sửa đổi khi cần thiết",
        "  • Thông báo công khai ít nhất 24 giờ trước khi có hiệu lực",
        "",
        "🚫 KHIẾU NẠI:",
        "  • Khiếu nại sai sự thật, dựng chuyện để hãm hại người khác: xử lý ban tối thiểu 7 ngày",
        "  • Giao dịch không có bằng chứng: ADMIN có quyền từ chối xử lý",
        ""
      ],
      "lineCount": 115
    },
    {
      "id": "tromcap",
      "title": "Trộm cắp tài sản",
      "icon": "💰",
      "summary": "Quy định bảo vệ rương, farm, vật phẩm, tài sản và deathchest/grave.",
      "lines": [
        "",
        "💰 TRỘM CẮP TÀI SẢN",
        "",
        "",
        "🔹 CHƯƠNG I: QUY ĐỊNH CHUNG 🔹",
        "",
        "",
        "❌ CÁC HÀNH VI TRỘM CẮP BỊ NGHIÊM CẤM TUYỆT ĐỐI:",
        "  • Trộm vật phẩm trong rương, barrel, hopper, shulker box, minecart chest của người khác khi chưa được cho phép",
        "  • Lén lấy tài nguyên / vật phẩm tại farm, kho đồ hoặc khu vực sinh sống của người khác",
        "  • Lợi dụng khu vực chưa claim (hoặc chưa bảo vệ) để lấy đồ hoặc phá rương",
        "  • Dùng alt account để trộm đồ hoặc chuyển tài sản sang tài khoản khác nhằm né xử phạt",
        "  • Cố tình chặn deathchest / grave không cho chủ sở hữu lấy lại đồ sau khi chết",
        "  • Lấy vật phẩm trong quá trình giao dịch khi chưa hoàn tất thỏa thuận (rút lại giữa chừng)",
        "  • Lấy cắp trang sức, đầu mob, item trong khung tranh (item frame) treo trong công trình người khác",
        "  • Lấy cắp hoa màu, cây trồng, nông sản trong farm của người khác khi chưa được phép",
        "  • Lấy cắp nguyên liệu từ máy tự động (super smelter, auto farm, mob grinder, v.v.)",
        "",
        "🟡 Mọi hành vi trên đều được xem là TRỘM CẮP TÀI SẢN và sẽ bị xử lý theo khung phạt",
        "",
        "",
        "✅ NGUYÊN TẮC TÔN TRỌNG TÀI SẢN:",
        "",
        "  • Tôn trọng hoàn toàn tài sản của người chơi khác, kể cả khi chưa được claim",
        "  • Khi cần sử dụng vật phẩm, rương, farm, thiết bị của người khác:",
        "    → BẮT BUỘC phải có sự cho phép RÕ RÀNG của chủ sở hữu TRƯỚC khi sử dụng",
        "  • Nếu không chắc chắn đồ đó có chủ hay không → HÃY HỎI trước khi lấy",
        "  • Nếu xảy ra tranh chấp, ADMIN sẽ kiểm tra log server để xác minh",
        "",
        "👥 ĐỐI TƯỢNG ÁP DỤNG:",
        "  • Tất cả người chơi trên máy chủ, không phân biệt cấp bậc",
        "",
        "📖 GIẢI THÍCH TỪ NGỮ:",
        "  • Trộm cắp: Hành vi lấy vật phẩm của người khác mà không được cho phép",
        "  • Tài sản: Bất kỳ vật phẩm, block, tài nguyên, nguyên liệu nào thuộc sở hữu của người chơi",
        "  • Deathchest / Grave: Khu vực chứa đồ của người chơi sau khi chết",
        "",
        "",
        "🔹 CHƯƠNG II: CÁC HÀNH VI BỊ CẤM & HÌNH THỨC PHÁT HIỆN 🔹",
        "",
        "",
        "⚠️ DANH MỤC HÀNH VI BỊ NGHIÊM CẤM (CHI TIẾT):",
        "",
        "  [1] Trộm rương / barrel / shulker:",
        "    → Mở rương của người khác, lấy toàn bộ hoặc một phần vật phẩm",
        "    → Lấy đồ từ hopper, dropper, dispenser kết nối với rương người khác",
        "",
        "  [2] Trộm farm:",
        "    → Thu hoạch lúa, cà rốt, khoai tây, nether wart trong farm người khác",
        "    → Lấy trứng, len, thịt từ động vật nuôi của người khác",
        "",
        "  [3] Trộm máy tự động:",
        "    → Lấy vật phẩm từ super smelter, auto crafter, mob grinder của người khác",
        "",
        "  [4] Lợi dụng chưa claim:",
        "    → Thấy khu vực chưa claim nhưng rõ ràng có dấu hiệu thuộc về ai đó → vẫn lấy",
        "",
        "  [5] Chặn deathchest / grave:",
        "    → Đặt block xung quanh, đào hố, đặt lava/nước để chủ nhân không lấy được đồ",
        "",
        "  [6] Dùng alt account để trộm:",
        "    → Tạo tài khoản phụ để trộm, sau đó chuyển đồ về main",
        "    → Dùng alt để tránh bị phát hiện danh tính thật",
        "",
        "  [7] Trộm trong giao dịch:",
        "    → Nhận đồ từ người mua/bán nhưng không trả đúng thỏa thuận",
        "    → Lấy đồ xong rồi bỏ chạy, logout",
        "",
        "  [8] Trộm item trong khung tranh / giá treo:",
        "    → Lấy đầu mob, vật phẩm trang trí trong item frame, armor stand của người khác",
        "",
        "🔍 HÌNH THỨC PHÁT HIỆN VI PHẠM:",
        "",
        "  • Phát hiện tự động:",
        "    → Log máy chủ ghi nhận ai đã mở rương, lấy vật phẩm, thời gian, tọa độ",
        "",
        "  • Phát hiện thủ công:",
        "    → Người chơi phát hiện mất đồ → kiểm tra rương/farm",
        "    → Báo cáo qua Ticket Discord kèm ảnh/video",
        "",
        "📸 GIÁ TRỊ PHÁP LÝ CỦA BẰNG CHỨNG:",
        "  • Server log: Giá trị cao nhất (do ADMIN khai thác, chính xác tuyệt đối)",
        "  • Video ghi hình: Giá trị cao (không cắt ghép)",
        "  • Ảnh chụp màn hình trước/sau: Giá trị trung bình (cần kèm log)",
        "  • Tố giác không bằng chứng: Chỉ để kiểm tra thêm, không đủ xử phạt",
        "",
        "",
        "🔹 CHƯƠNG III: XỬ LÝ VI PHẠM & HÌNH PHẠT 🔹",
        "",
        "",
        "⛔ NGUYÊN TẮC XỬ LÝ:",
        "",
        "  • Phát hiện trộm cắp → xử lý theo khung phạt chính thức",
        "  • Tài sản bị trộm (nếu còn trong log) sẽ được hoàn trả nguyên vẹn",
        "  • Nếu tài sản đã bị tiêu hủy hoặc chuyển đi, người trộm phải bồi thường 100% giá trị",
        "  • Người bị hại cố tình dựng chuyện, khai gian → xử lý ngược lại (ban tối thiểu 7 ngày)",
        "",
        "📊 KHUNG XỬ PHẠT (THAM KHẢO):",
        "",
        "  • Lần 1 (vi phạm lần đầu, số lượng nhỏ):",
        "    → Ban tạm thời 3 ngày",
        "    → Hoàn trả / bồi thường toàn bộ tài sản đã trộm",
        "",
        "  • Lần 2 tái phạm:",
        "    → Ban tạm thời 7 ngày",
        "    → Hoàn trả + phạt thêm 50% giá trị tài sản đã trộm",
        "",
        "  • Lần 3 tái phạm nhiều lần hoặc số lượng lớn:",
        "    → Ban tạm thời 14 ngày",
        "    → Hoàn trả + phạt thêm 100% giá trị tài sản đã trộm",
        "",
        "⚠️ TÌNH TIẾT TĂNG NẶNG (CÓ THỂ BAN NẶNG HƠN HOẶC BAN VĨNH VIỄN):",
        "  • Trộm cắp số lượng lớn",
        "  • Trộm cắp có tổ chức (nhiều người cùng trộm)",
        "  • Trộm cắp nhiều lần trong thời gian ngắn",
        "  • Trộm cắp kèm phá hoại công trình",
        "  • Sử dụng alt account để trộm và tẩu tán tài sản",
        "    → Có thể bị ban vĩnh viễn ngay lần đầu",
        "",
        "  • ÁP DỤNG VỚI MỌI TÀI KHOẢN LIÊN QUAN:",
        "    → Tài khoản chính, tài khoản phụ (Alt Account)",
        "",
        "📋 TRÁCH NHIỆM CỦA NGƯỜI CHƠI:",
        "",
        "  ✅ ĐỂ BẢO VỆ TÀI SẢN CỦA MÌNH:",
        "     → Nên claim khu vực sinh sống và kho đồ",
        "     → Không để đồ quý giá ở nơi dễ bị lấy cắp",
        "",
        "  ✅ KHI BỊ TRỘM TÀI SẢN:",
        "     → Ghi lại thời gian phát hiện, tọa độ, vật phẩm mất",
        "     → Ghi hình hoặc chụp ảnh khu vực bị trộm",
        "     → Báo cáo ADMIN qua Ticket Discord càng sớm càng tốt (log sẽ lưu 7-30 ngày)",
        "",
        "  ✅ KHI VÔ TÌNH LẤY ĐỒ CỦA NGƯỜI KHÁC:",
        "     → Trả lại NGAY LẬP TỨC",
        "     → Xin lỗi chủ sở hữu",
        "     → Báo ADMIN để xác nhận đã giải quyết",
        "     → Nếu thành khẩn, có thể bỏ qua hoặc giảm nhẹ hình phạt",
        "",
        "⚖️ THẨM QUYỀN & TRÁCH NHIỆM CỦA ADMIN:",
        "",
        "  • Quyền: Tra cứu log máy chủ để xác định người lấy đồ",
        "  • Quyền: Teleport đến kiểm tra hiện trường",
        "  • Quyền: Hoàn trả tài sản bị mất (nếu còn dữ liệu)",
        "  • Quyền: Ban tạm thời, vĩnh viễn tùy mức độ",
        "  • Trách nhiệm: Phản hồi trong vòng 24-48 giờ",
        "  • Trách nhiệm: Lưu trữ lịch sử vi phạm trộm cắp",
        "",
        "",
        "🔹 CHƯƠNG IV: ĐIỀU KHOẢN THI HÀNH 🔹",
        "",
        "",
        "📅 HIỆU LỰC THI HÀNH:",
        "  • Quy định có hiệu lực từ ngày công bố chính thức",
        "",
        "✏️ SỬA ĐỔI, BỔ SUNG:",
        "  • Đội Ngũ ADMIN có quyền sửa đổi khi cần thiết",
        "  • Thông báo công khai ít nhất 24 giờ trước khi có hiệu lực",
        "",
        "🚫 KHIẾU NẠI:",
        "  • Khiếu nại sai sự thật, dựng chuyện để hãm hại người khác: xử lý ban tối thiểu 7 ngày",
        "  • Không có bằng chứng log/video → ADMIN có quyền từ chối xử lý",
        ""
      ],
      "lineCount": 112
    },
    {
      "id": "farm",
      "title": "Máy farm & hiệu năng",
      "icon": "🌍",
      "summary": "Quy định xây farm, vùng cấm 2000 block từ Spawn và xử lý lag machine.",
      "lines": [
        "",
        "🌍 QUY ĐỊNH VỀ VIỆC XÂY CÁC MÁY FARM",
        "",
        "",
        "🔹 CHƯƠNG I: QUY ĐỊNH CHUNG 🔹",
        "",
        "",
        "❌ CÁC LOẠI FARM BỊ CẤM TRONG PHẠM VI 2000 BLOCK TỪ SPAWN:",
        "",
        "  • Không xây bất kỳ loại farm nào trong phạm vi 2000 block tính từ Spawn (trung tâm máy chủ)",
        "",
        "  Bao gồm nhưng không giới hạn:",
        "    → Mob Farm (tất cả các loại: creeper, skeleton, zombie, spider, v.v.)",
        "    → XP Farm (farm kinh nghiệm, enderman farm, piglin farm, v.v.)",
        "    → Iron Farm (farm sắt, golem farm)",
        "    → Gold Farm (farm vàng, zombified piglin farm)",
        "    → Raid Farm (farm raid, pillager farm)",
        "    → Guardian Farm (farm thủy thạch, guardian)",
        "    → Slime Farm (farm chất nhờn, slime)",
        "    → Witch Farm (farm phù thủy)",
        "    → Khu vực trade / trao đổi với dân làng",
        "    → Các loại farm tương tự gây ảnh hưởng đến hiệu năng server",
        "",
        "",
        "🟡 CÁC LOẠI FARM BỊ HẠN CHẾ NẾU GÂY LAG (KHÔNG PHÂN BIỆT VỊ TRÍ):",
        "",
        "  • Số lượng mob lớn bất thường (≥150 mob cùng lúc trong một khu vực)",
        "  • Redstone phức tạp (clock quá nhanh, hopper spam không kiểm soát, redstone loop kéo dài)",
        "  • Spam entity (entity stacking, minecart, boat, armor stand số lượng lớn ≥50 cùng lúc)",
        "  • Farm sử dụng piston liên tục (tick rate cao, gây lag cập nhật block)",
        "  • Các farm gây ảnh hưởng đến TPS (ticks per second) của server",
        "",
        "",
        "📌 LÝ DO ÁP DỤNG:",
        "",
        "  • Tránh gây lag server nghiêm trọng (TPS, MSPT, entity tick)",
        "  • Tránh ảnh hưởng đến trải nghiệm chung của toàn bộ người chơi trên server",
        "  • Giữ khu vực Spawn sạch đẹp, thoáng mát và công bằng cho người chơi mới",
        "  • Đảm bảo hiệu năng server ổn định cho mọi hoạt động",
        "",
        "",
        "✅ NGUYÊN TẮC XÂY DỰNG FARM HỢP LỆ:",
        "",
        "  • Farm chỉ được xây ngoài phạm vi 2000 block tính từ Spawn",
        "  • Nếu farm bị ADMIN yêu cầu gỡ vì lý do lag → phải chấp hành ngay",
        "  • Khi farm gây lag dù ở bất kỳ đâu, ADMIN có quyền yêu cầu chỉnh sửa hoặc xóa bỏ",
        "",
        "",
        "👥 ĐỐI TƯỢNG ÁP DỤNG:",
        "  • Tất cả người chơi trên máy chủ, không phân biệt cấp bậc",
        "",
        "📖 GIẢI THÍCH TỪ NGỮ:",
        "  • Farm: Công trình được xây dựng nhằm tự động thu hoạch tài nguyên / kinh nghiệm",
        "  • Lag: Hiện tượng giật, chậm, delay do server quá tải",
        "  • TPS (Tick Per Second): Số tick server xử lý mỗi giây (tối đa 20, càng thấp càng lag)",
        "  • MSPT (Milliseconds Per Tick): Thời gian xử lý mỗi tick (càng cao càng lag)",
        "  • Lag Machine: Công trình cố tình xây dựng để làm lag hoặc crash server",
        "",
        "",
        "🔹 CHƯƠNG II: CÁC HÀNH VI BỊ CẤM & HÌNH THỨC PHÁT HIỆN 🔹",
        "",
        "",
        "⚠️ DANH MỤC HÀNH VI BỊ NGHIÊM CẤM (CHI TIẾT):",
        "",
        "  [1] Xây farm trong phạm vi cấm:",
        "    → Bất kỳ loại farm nào trong 2000 block từ Spawn",
        "    → Kể cả farm nhỏ, farm thủ công cũng có thể bị xóa",
        "",
        "  [2] Farm gây lag nặng:",
        "    → Tích tụ quá nhiều mob (>100) không kill kịp",
        "    → Redstone clock chạy quá nhanh, hopper chain quá dài",
        "    → Spam minecart, boat, armor stand không cần thiết",
        "",
        "  [3] Không chấp hành yêu cầu của ADMIN:",
        "    → Được yêu cầu sửa/gỡ farm nhưng cố tình không làm",
        "    → Lén xây lại farm sau khi đã bị xóa",
        "",
        "  [4] Cố tình xây lag machine:",
        "    → Tạo vòng lặp redstone vô hạn",
        "    → Spam entity khủng bố server hàng loạt",
        "    → Dùng cơ chế game để crash server",
        "",
        "🔍 HÌNH THỨC PHÁT HIỆN VI PHẠM:",
        "",
        "  • Phát hiện tự động:",
        "    → Hệ thống giám sát TPS/MSPT tự động báo động khi lag",
        "    → Plugin phát hiện entity spam, redstone loop",
        "",
        "  • Phát hiện thủ công:",
        "    → ADMIN tuần tra kiểm tra khu vực xung quanh Spawn",
        "    → Người chơi báo cáo lag qua Ticket Discord",
        "",
        "📸 GIÁ TRỊ PHÁP LÝ CỦA BẰNG CHỨNG:",
        "  • Server log + TPS log: Giá trị cao nhất (do ADMIN khai thác)",
        "  • Video ghi hình lag: Giá trị cao (không cắt ghép)",
        "  • Ảnh chụp màn hình farm: Giá trị trung bình (cần kèm tọa độ)",
        "",
        "",
        "🔹 CHƯƠNG III: XỬ LÝ VI PHẠM & HÌNH PHẠT 🔹",
        "",
        "",
        "⛔ NGUYÊN TẮC XỬ LÝ:",
        "",
        "  • Phát hiện farm trong vùng cấm → xóa ngay lập tức ( không đền bù )",
        "  • Farm gây lag dù ở đâu → yêu cầu chỉnh sửa hoặc xóa",
        "  • Không chấp hành → xử lý theo khung phạt",
        "",
        "📊 KHUNG XỬ PHẠT (THAM KHẢO):",
        "",
        "  • Lần 1 (vi phạm lần đầu):",
        "    → Cảnh báo bằng văn bản",
        "    → Xóa toàn bộ farm vi phạm",
        "",
        "  • Lần 2 (tái phạm):",
        "    → Ban tạm thời 3 ngày",
        "    → Xóa farm vi phạm",
        "",
        "  • Lần 3 (tái phạm nhiều lần):",
        "    → Ban tạm thời 7 ngày",
        "    → Xóa farm vi phạm",
        "",
        "⚠️ TÌNH TIẾT TĂNG NẶNG (CÓ THỂ BAN NẶNG HƠN):",
        "",
        "  • Xây farm trong vùng cấm sau khi đã bị cảnh báo",
        "  • Xây farm gây lag nghiêm trọng ảnh hưởng toàn server",
        "",
        "🔴 ĐẶC BIỆT - LAG MACHINE:",
        "",
        "  • Mọi hành vi cố tình xây dựng lag machine nhằm làm lag hoặc crash server:",
        "    → BAN VĨNH VIỄN NGAY LẬP TỨC",
        "    → Không cảnh báo – Không giảm án – Không unban",
        "    → Áp dụng cho mọi tài khoản liên quan (Alt Account + cùng IP)",
        "",
        "📋 TRÁCH NHIỆM CỦA NGƯỜI CHƠI:",
        "",
        "  ✅ KHI XÂY DỰNG FARM:",
        "     → Kiểm tra khoảng cách đến Spawn (dùng /spawn hoặc F3 để xem tọa độ)",
        "     → Không xây farm nếu trong phạm vi 2000 block",
        "",
        "  ✅ KHI PHÁT HIỆN LAG:",
        "     → Báo ADMIN qua Ticket Discord kèm tọa độ khu vực nghi ngờ",
        "     → Không tự ý phá farm của người khác dù họ gây lag",
        "",
        "  ✅ KHI ĐƯỢC ADMIN YÊU CẦU:",
        "     → Hợp tác, tắt farm ngay lập tức",
        "     → Sửa hoặc di dời farm theo hướng dẫn",
        "",
        "⚖️ THẨM QUYỀN & TRÁCH NHIỆM CỦA ADMIN:",
        "",
        "  • Quyền: Kiểm tra bất kỳ farm nào trên server",
        "  • Quyền: Yêu cầu tắt, sửa, hoặc xóa farm gây lag",
        "  • Quyền: Teleport đến bất kỳ vị trí nào để kiểm tra",
        "  • Quyền: Ban vĩnh viễn đối với lag machine",
        "  • Trách nhiệm: Phản hồi báo cáo lag trong vòng 24 giờ",
        "  • Trách nhiệm: Thông báo lý do xóa farm cho người chơi",
        "",
        "",
        "🔹 CHƯƠNG IV: ĐIỀU KHOẢN THI HÀNH 🔹",
        "",
        "",
        "📅 HIỆU LỰC THI HÀNH:",
        "  • Quy định có hiệu lực từ ngày công bố chính thức",
        "  • Các farm đã xây trước ngày ban hành phải được di dời hoặc phá bỏ trong vòng 7 ngày",
        "",
        "✏️ SỬA ĐỔI, BỔ SUNG:",
        "  • Đội Ngũ ADMIN có quyền sửa đổi khi cần thiết",
        "  • Thông báo công khai ít nhất 24 giờ trước khi có hiệu lực",
        "",
        "🚫 KHIẾU NẠI:",
        "  • Khiếu nại sai sự thật, dựng chuyện để hãm hại người khác: xử lý ban tối thiểu 7 ngày",
        ""
      ],
      "lineCount": 114
    },
    {
      "id": "trachnhiem",
      "title": "Trách nhiệm người chơi",
      "icon": "⚖️",
      "summary": "Trách nhiệm đọc luật, báo cáo vi phạm, không trả đũa và bảo mật tài khoản.",
      "lines": [
        "",
        "⚖️ QUY ĐỊNH TRÁCH NHIỆM NGƯỜI CHƠI",
        "",
        "",
        "🔹 CHƯƠNG I: TRÁCH NHIỆM KHI THAM GIA SERVER 🔹",
        "",
        "",
        "🟡 KHI BẠN THAM GIA MÁY CHỦ:",
        "",
        "  • Khi bạn tham gia máy chủ, điều đó đồng nghĩa với việc bạn CHẤP NHẬN TOÀN BỘ LUẬT của server",
        "  • Luật vẫn được áp dụng ngay cả khi bạn:",
        "    → Không thấy luật",
        "    → Không đọc luật",
        "    → Không sử dụng Discord",
        "    → Không tìm hiểu trước",
        "    → Là người chơi mới (newbie)",
        "    → Chơi lại sau thời gian dài không online",
        "",
        "❌ KHÔNG CHẤP NHẬN CÁC LÝ DO SAU ĐỂ NÉ TRÁNH HOẶC GIẢM NHẸ HÌNH PHẠT:",
        "",
        "⚠️ Mọi người chơi đều chịu trách nhiệm TỰ TÌM HIỂU LUẬT TRƯỚC KHI CHƠI",
        "",
        "  • Luật được đăng công khai tại: Discord",
        "  • Việc không đọc luật KHÔNG phải là lý do hợp lệ để vi phạm",
        "",
        "",
        "🔹 CHƯƠNG II: TRÁCH NHIỆM KHI XẢY RA TRANH CHẤP 🔹",
        "",
        "",
        "📌 LƯU Ý KHI NGƯỜI CHƠI KHÁC VI PHẠM LUẬT:",
        "",
        "  Nếu người chơi khác vi phạm luật trước, hãy thực hiện các bước sau:",
        "",
        "  • 📸 Chụp ảnh màn hình (screenshot) hành vi vi phạm",
        "  • 🎥 Quay video toàn bộ quá trình (nếu có thể)",
        "  • 💬 Lưu lại chat trong game (chụp hoặc copy log)",
        "  • 📝 Ghi lại thời gian, tọa độ, tên người vi phạm",
        "  • 🎫 Gửi báo cáo qua Ticket Discord cho Đội Ngũ ADMIN",
        "",
        "",
        "❗ QUY TẮC VÀNG - KHÔNG TỰ Ý TRẢ ĐŨA:",
        "",
        "  • BẮT BUỘC: Không được tự ý trả đũa hoặc vi phạm lại luật",
        "  • Nếu bạn bị phá hoại → không được phá hoại lại",
        "  • Nếu bạn bị trộm → không được trộm lại",
        "  • Nếu bạn bị xúc phạm → không được xúc phạm lại",
        "",
        "  ⚠️ HẬU QUẢ: Nếu bạn tự ý trả đũa, CẢ HAI bên đều bị xử lý theo đúng quy định",
        "  → Bạn sẽ trở thành người vi phạm thay vì là nạn nhân",
        "",
        "",
        "📋 TRÁCH NHIỆM CỤ THỂ CỦA NGƯỜI CHƠI:",
        "",
        "  ✅ TÌM HIỂU LUẬT:",
        "     → Đọc toàn bộ quy định trước khi bắt đầu chơi",
        "     → Cập nhật luật mới khi có thông báo (theo dõi Discord)",
        "",
        "  ✅ BÁO CÁO VI PHẠM:",
        "     → Chỉ báo cáo khi có bằng chứng rõ ràng",
        "     → Không báo cáo sai sự thật, không dựng chuyện",
        "     → Hợp tác với ADMIN trong quá trình xử lý",
        "",
        "  ✅ ĐÓNG GÓP:",
        "     → Báo lỗi bug, exploit nếu phát hiện",
        "     → Góp ý xây dựng server",
        "     → Giúp đỡ người chơi mới hiểu luật",
        "",
        "",
        "⚠️ TRÁCH NHIỆM VỚI TÀI KHOẢN:",
        "",
        "  • Bạn hoàn toàn chịu trách nhiệm với mọi hành vi phát sinh từ tài khoản của mình",
        "  • Không cho mượn tài khoản (nếu có, bạn tự chịu rủi ro)",
        "  • Nếu tài khoản bị hack, hãy báo ADMIN ngay để khóa tạm thời",
        "  • Mọi vi phạm từ tài khoản của bạn (dù do bạn hay người mượn) → bạn vẫn bị xử lý",
        "",
        "",
        "👥 ĐỐI TƯỢNG ÁP DỤNG:",
        "  • Tất cả người chơi trên máy chủ, không phân biệt cấp bậc",
        "  • Áp dụng cho mọi tài khoản liên quan (Alt Account)",
        "  • Áp dụng cho TẤT CẢ tài khoản có cùng IP",
        "",
        "",
        "🔹 CHƯƠNG III: HẬU QUẢ KHI KHÔNG TUÂN THỦ 🔹",
        "",
        "",
        "📊 VI PHẠM TRÁCH NHIỆM NGƯỜI CHƠI:",
        "",
        "  • Không tìm hiểu luật dẫn đến vi phạm:",
        "    → Vẫn bị xử lý như bình thường, KHÔNG được giảm án",
        "",
        "  • Cố tình báo cáo sai sự thật, dựng chuyện hãm hại người khác:",
        "    → Ban tối thiểu 7 ngày (có thể ban vĩnh viễn nếu nghiêm trọng)",
        "",
        "  • Tự ý trả đũa, vi phạm luật để trả thù:",
        "    → Cả hai bên đều bị xử lý theo đúng khung phạt tương ứng",
        "    → Không chấp nhận lý do 'nó làm trước'",
        "",
        "  • Cho mượn tài khoản để người khác vi phạm:",
        "    → Chủ tài khoản và người mượn đều bị xử lý",
        "",
        "",
        "🔹 CHƯƠNG IV: ĐIỀU KHOẢN THI HÀNH 🔹",
        "",
        "",
        "📅 HIỆU LỰC THI HÀNH:",
        "  • Quy định có hiệu lực từ ngày công bố chính thức",
        "  • Mọi người chơi đều được coi là đã đọc và chấp nhận luật khi tiếp tục chơi trên server",
        "",
        "✏️ SỬA ĐỔI, BỔ SUNG:",
        "  • Đội Ngũ ADMIN có quyền sửa đổi khi cần thiết",
        "  • Thông báo công khai ít nhất 24 giờ trước khi có hiệu lực",
        "",
        "🚫 KHIẾU NẠI:",
        "  • Mọi khiếu nại về quyết định của ADMIN phải được gửi qua Ticket Discord",
        "  • Không gây hấn, không spam, không chửi bới ADMIN khi bị xử lý (sẽ bị tăng nặng hình phạt)",
        ""
      ],
      "lineCount": 72
    },
    {
      "id": "vnd",
      "title": "Cấm giao dịch tiền thật",
      "icon": "💵",
      "summary": "Cấm mua bán vật phẩm, tài khoản, dịch vụ bằng tiền thật hoặc giao dịch ngoài game.",
      "lines": [
        "",
        "💵 CẤM GIAO DỊCH TIỀN THẬT",
        "",
        "",
        "🔹 CHƯƠNG I: QUY ĐỊNH CHUNG 🔹",
        "",
        "",
        "❌ CÁC HÀNH VI BỊ NGHIÊM CẤM TUYỆT ĐỐI:",
        "",
        "  • Mua bán vật phẩm, tài khoản, dịch vụ trong game bằng tiền thật (VND, USD, vàng, crypto, v.v.)",
        "  • Rủ rê, quảng cáo hoặc trung gian giao dịch tiền thật giữa các người chơi",
        "  • Nhận tiền thật để làm dịch vụ trong game (xây nhà, đào mỏ, farm đồ, v.v.)",
        "  • Bán acc Minecraft / alt account có liên quan đến server dưới mọi hình thức",
        "",
        "",
        "🟡 Mọi hành vi trên đều bị xem là VI PHẠM NGHIÊM TRỌNG và sẽ bị xử lý ngay lập tức",
        "",
        "",
        "📌 LÝ DO CẤM:",
        "",
        "  • Đảm bảo công bằng giữa tất cả người chơi (pay-to-win bị cấm tuyệt đối)",
        "  • Tránh tranh chấp, lừa đảo liên quan đến tiền thật (server không thể đứng ra bảo vệ)",
        "  • Tuân thủ quy định của nhà phát hành Minecraft (EULA - End User License Agreement)",
        "  • Bảo vệ người chơi khỏi các giao dịch rủi ro, lừa đảo ngoài đời",
        "",
        "",
        "👥 ĐỐI TƯỢNG ÁP DỤNG:",
        "  • Tất cả người chơi trên máy chủ, không phân biệt cấp bậc",
        "",
        "",
        "🔹 CHƯƠNG II: CÁC HÀNH VI BỊ CẤM (CHI TIẾT) 🔹",
        "",
        "",
        "⚠️ DANH MỤC HÀNH VI BỊ NGHIÊM CẤM (CHI TIẾT):",
        "",
        "  [1] Mua bán vật phẩm bằng tiền thật:",
        "    → Bán kim cương, netherite, cổ vật, gear, pet, v.v. lấy tiền thật",
        "    → Mua item bằng tiền thật",
        "",
        "  [2] Mua bán tài khoản:",
        "    → Bán lại tài khoản Minecraft đã chơi trên server cho người khác",
        "    → Mua tài khoản có sẵn vật phẩm để vào server",
        "",
        "  [3] Dịch vụ bằng tiền thật:",
        "    → Nhận tiền để xây nhà, căn cứ, farm thay",
        "",
        "  [4] Hối lộ ADMIN / Mod:",
        "    → Đưa tiền, thẻ cào, vật phẩm ngoài game để ``ADMIN / STAFF / HELPER`` bỏ qua lỗi, ban người khác",
        "    → Nhờ ADMIN can thiệp trái quy định vì lợi ích cá nhân",
        "",
        "  [5] Quảng cáo giao dịch tiền thật:",
        "    → Gửi link website bán đồ game trong chat",
        "    → Rủ rê người khác mua bán bằng tiền thật qua Discord hoặc in-game",
        "",
        "  [6] Giao dịch ngoài game (off-game):",
        "    → Giao dịch qua chuyển khoản ngân hàng, ví điện tử, thẻ cào, mã giftcard",
        "    → Bán item lấy tiền mặt trực tiếp",
        "",
        "",
        "🔍 HÌNH THỨC PHÁT HIỆN VI PHẠM:",
        "",
        "  • Phát hiện tự động:",
        "    → Log chat ghi nhận nội dung đáng ngờ",
        "",
        "  • Phát hiện thủ công:",
        "    → ADMIN/Mod đọc chat, kiểm tra người chơi",
        "    → Người chơi tố giác qua Ticket Discord (kèm ảnh/video)",
        "    → ADMIN điều tra giao dịch bất thường",
        "",
        "📸 GIÁ TRỊ PHÁP LÝ CỦA BẰNG CHỨNG:",
        "  • Chat log công khai: Giá trị cao nhất (rõ ràng hành vi)",
        "  • Ảnh chụp màn hình DM Discord: Giá trị cao (nếu có thể xác thực)",
        "  • Video ghi hình: Giá trị cao (không cắt ghép)",
        "  • Tố giác không bằng chứng: Chỉ để kiểm tra thêm, không đủ xử phạt",
        "",
        "",
        "🔹 CHƯƠNG III: XỬ LÝ VI PHẠM & HÌNH PHẠT 🔹",
        "",
        "",
        "⛔ NGUYÊN TẮC XỬ LÝ:",
        "",
        "  • Phát hiện giao dịch tiền thật → xử lý ngay lập tức, KHÔNG CẢNH BÁO TRƯỚC",
        "  • Không chấp nhận bất kỳ lời giải thích hay rút lại nào sau đó",
        "  • Toàn bộ tài sản liên quan đến giao dịch tiền thật sẽ bị tịch thu",
        "",
        "📊 HÌNH PHẠT CHÍNH THỨC:",
        "",
        "  • Bất kỳ hành vi giao dịch tiền thật nào (lần đầu):",
        "    → BAN VĨNH VIỄN NGAY LẬP TỨC",
        "    → Không cảnh báo – Không giảm án – Không unban",
        "    → Tịch thu toàn bộ tài sản trong game",
        "",
        "  • Quảng cáo / rủ rê giao dịch tiền thật:",
        "    → Ban vĩnh viễn ngay lập tức",
        "",
        "  • Hối lộ ADMIN / Mod:",
        "    → Ban vĩnh viễn ngay lập tức (cả người hối lộ và người nhận nếu có)",
        "",
        "  • Tái phạm (dùng alt account để tiếp tục giao dịch):",
        "    → Ban vĩnh viễn + IP",
        "",
        "  • ÁP DỤNG VỚI MỌI TÀI KHOẢN LIÊN QUAN:",
        "    → Tài khoản chính, tài khoản phụ (Alt Account)",
        "    → Tất cả tài khoản dùng chung IP",
        "    → Nếu một tài khoản giao dịch tiền thật → TOÀN BỘ tài khoản trong IP đều bị ban vĩnh viễn",
        "",
        "",
        "📋 TRÁCH NHIỆM CỦA NGƯỜI CHƠI:",
        "",
        "  ✅ Nếu được ai đó mời giao dịch tiền thật:",
        "     → Từ chối ngay lập tức",
        "     → Chụp ảnh, ghi lại nội dung, tên người mời",
        "     → Báo ADMIN qua Ticket Discord để xử lý",
        "     → Không tham gia dù chỉ một lần",
        "",
        "  ✅ Nếu bạn vô tình nhận được đề nghị:",
        "     → Không chuyển khoản, không gửi tiền",
        "     → Báo cáo ngay để bảo vệ chính mình",
        "",
        "",
        "⚠️ LƯU Ý QUAN TRỌNG:",
        "",
        "  • Server KHÔNG chịu trách nhiệm giải quyết tranh chấp phát sinh từ giao dịch tiền thật",
        "  • Bạn tự chịu rủi ro 100% nếu vẫn cố tình giao dịch (mất tiền, bị lừa, không được hỗ trợ)",
        "  • Hình phạt áp dụng cho CẢ HAI bên (người mua và người bán)",
        "",
        "",
        "🔹 CHƯƠNG IV: ĐIỀU KHOẢN THI HÀNH 🔹",
        "",
        "",
        "📅 HIỆU LỰC THI HÀNH:",
        "  • Quy định có hiệu lực từ ngày công bố chính thức",
        "",
        "✏️ SỬA ĐỔI, BỔ SUNG:",
        "  • Đội Ngũ ADMIN có quyền sửa đổi khi cần thiết",
        "  • Thông báo công khai ít nhất 24 giờ trước khi có hiệu lực",
        "",
        "🚫 KHIẾU NẠI:",
        "  • Không chấp nhận khiếu nại đối với các trường hợp bị ban vì giao dịch tiền thật",
        ""
      ],
      "lineCount": 87
    },
    {
      "id": "taikhoan",
      "title": "Trách nhiệm tài khoản",
      "icon": "🔐",
      "summary": "Chính sách cho mượn tài khoản, dùng chung IP, alt account và giải trình.",
      "lines": [
        "",
        "⚠️ TRÁCH NHIỆM VỚI TÀI KHOẢN",
        "",
        "",
        "🔹 CHƯƠNG I: QUY ĐỊNH CHUNG 🔹",
        "",
        "",
        "❌ CẤM CHO MƯỢN TÀI KHOẢN CHO NGƯỜI LẠ:",
        "",
        "  • Vui lòng KHÔNG cung cấp tài khoản cho người lạ mượn",
        "  • Bạn hoàn toàn chịu trách nhiệm với mọi hành vi phát sinh từ tài khoản của mình",
        "  • Nếu cho mượn, bạn tự chịu rủi ro 100% (không được khiếu nại sau đó)",
        "  • Mọi vi phạm từ tài khoản của bạn (dù do bạn hay người mượn) → bạn vẫn bị xử lý",
        "",
        "",
        "🔴 DÙNG CHUNG IP - CHÍNH SÁCH BAN HÀNG LOẠT:",
        "",
        "  • Trường hợp dùng chung IP (cùng WiFi, cùng nhà, cùng trọ, cùng quán net, v.v.):",
        "",
        "    → Nếu MỘT tài khoản trong IP bị ban (vì bất kỳ lý do vi phạm nào)",
        "    → TẤT CẢ những tài khoản có cùng IP với tài khoản vi phạm đều bị BAN THEO",
        "    → Áp dụng cho mọi loại vi phạm (PvP, hack, phá hoại, scam, trộm cắp, chat, v.v.)",
        "",
        "",
        "❌ KHÔNG CHẤP NHẬN CÁC LÝ DO SAU:",
        "",
        "  • 'Đó là em trai / chị gái / anh trai / bố mẹ em'",
        "  • 'Đó là bạn cùng phòng / bạn cùng lớp / người thân của em'",
        "  • 'Em cho mượn acc, người ta phá chứ em không phá'",
        "  • 'Chúng em dùng chung wifi, em không kiểm soát được'",
        "",
        "",
        "✅ CÁCH DUY NHẤT ĐỂ TRÁNH BỊ BAN OAN:",
        "",
        "  • Quản lý người dùng chung IP của bạn (người thân, bạn cùng nhà)",
        "  • Không cho mượn tài khoản dưới bất kỳ hình thức nào",
        "  • Chỉ chơi với những người đáng tin cậy khi dùng chung IP",
        "  • Nếu phát hiện người trong IP vi phạm, hãy báo ADMIN trước để được xem xét",
        "",
        "",
        "👥 ĐỐI TƯỢNG ÁP DỤNG:",
        "  • Tất cả người chơi trên máy chủ, không phân biệt cấp bậc",
        "  • Áp dụng cho mọi tài khoản liên quan (Alt Account)",
        "  • Áp dụng cho TẤT CẢ tài khoản có cùng IP (cùng WiFi, cùng nhà, cùng quán net)",
        "",
        "📖 GIẢI THÍCH TỪ NGỮ:",
        "  • IP: Địa chỉ mạng duy nhất của mỗi kết nối internet",
        "  • Dùng chung IP: Nhiều người dùng chung một đường mạng (WiFi nhà, quán net, VPN, v.v.)",
        "  • Alt Account: Tài khoản phụ, tài khoản thay thế của cùng một người chơi",
        "",
        "",
        "🔹 CHƯƠNG II: HẬU QUẢ KHI VI PHẠM 🔹",
        "",
        "",
        "📊 HÌNH PHẠT ÁP DỤNG:",
        "",
        "  • Đối với chủ tài khoản cho mượn acc (dù người mượn vi phạm):",
        "    → Bị xử lý Y HỆT như người vi phạm (ban đúng khung phạt tương ứng)",
        "    → Không chấp nhận lý do 'đó không phải mình làm'",
        "",
        "  • Đối với dùng chung IP:",
        "    → Nếu một tài khoản bị ban vĩnh viễn → TOÀN BỘ tài khoản trong IP đều bị ban vĩnh viễn",
        "    → Nếu một tài khoản bị ban tạm thời → các tài khoản khác trong IP có thể bị ban tạm thời hoặc cảnh báo",
        "    → ADMIN có quyền quyết định mức độ dựa trên tình huống cụ thể",
        "",
        "  • Tái phạm sau khi đã bị cảnh báo:",
        "    → Có thể bị ban vĩnh viễn ngay lập tức",
        "",
        "",
        "📋 TRÁCH NHIỆM CỦA NGƯỜI CHƠI:",
        "",
        "  ✅ KHI CÓ NGƯỜI MƯỢN TÀI KHOẢN:",
        "     → Từ chối ngay lập tức",
        "     → Giải thích với họ về chính sách của server",
        "     → Nếu họ ép buộc hoặc spam, báo ADMIN",
        "",
        "  ✅ KHI PHÁT HIỆN NGƯỜI DÙNG CHUNG IP VI PHẠM:",
        "     → Nhắc nhở họ dừng lại (nếu có thể)",
        "     → Báo ADMIN trước khi bị ban để được hỗ trợ",
        "     → Không bao che hoặc tiếp tay cho vi phạm",
        "",
        "  ✅ KHI VÔ TÌNH BỊ BAN DO DÙNG CHUNG IP:",
        "     → Gửi ticket giải trình lên ADMIN",
        "     → Cung cấp bằng chứng về việc bạn không liên quan (nếu có)",
        "     → ADMIN sẽ xem xét và có thể gỡ ban nếu đủ cơ sở",
        "     📌 CÁC CƠ SỞ ĐỂ ADMIN XEM XÉT GỠ BAN:",
        "        • Bạn chưa từng có bất kỳ vi phạm nào trước đó (lịch sử sạch)",
        "        • Bạn đã chủ động báo ADMIN ngay khi phát hiện người cùng IP vi phạm",
        "        • Bạn có bằng chứng chứng minh bạn không liên quan đến hành vi vi phạm (video, ảnh, log)",
        "        • Người vi phạm thừa nhận và xác nhận bạn không liên quan (qua chat hoặc ticket)",
        "        • Khoảng thời gian bạn và người vi phạm hoạt động KHÔNG trùng nhau (log chứng minh)",
        "        • Bạn đã thay đổi mật khẩu, bảo mật tài khoản sau khi biết sự việc",
        "        • Bạn chứng minh được mình là nạn nhân của việc dùng chung IP bất đắc dĩ (quán net, chung cư, v.v.)",
        "     ❌ CÁC TRƯỜNG HỢP KHÔNG ĐỦ CƠ SỞ ĐỂ GỠ BAN:",
        "        • 'Tôi không biết người đó' nhưng không có bằng chứng",
        "        • 'Đó là em trai / bạn cùng phòng tôi' nhưng không quản lý được",
        "        • Báo ADMIN sau khi đã bị ban quá lâu (≥1 ngày)",
        "        • Có tiền sử vi phạm trước đó (dù là lỗi nhỏ)",
        "        • Không cung cấp được bất kỳ bằng chứng nào để chứng minh sự vô tội",
        "",
        "",
        "",
        "⚖️ THẨM QUYỀN & TRÁCH NHIỆM CỦA ADMIN:",
        "",
        "  • Quyền: Kiểm tra IP và các tài khoản liên quan",
        "  • Quyền: Ban toàn bộ tài khoản trong cùng IP khi phát hiện vi phạm",
        "  • Quyền: Từ chối giải trình nếu bằng chứng không rõ ràng",
        "  • Trách nhiệm: Ghi lại lý do ban để người chơi biết",
        "  • Trách nhiệm: Xem xét khiếu nại nếu có đủ bằng chứng chứng minh không liên quan",
        "",
        "",
        "🔹 CHƯƠNG III: ĐIỀU KHOẢN THI HÀNH 🔹",
        "",
        "",
        "📅 HIỆU LỰC THI HÀNH:",
        "  • Quy định có hiệu lực từ ngày công bố chính thức",
        "",
        "✏️ SỬA ĐỔI, BỔ SUNG:",
        "  • Đội Ngũ ADMIN có quyền sửa đổi khi cần thiết",
        "  • Thông báo công khai ít nhất 24 giờ trước khi có hiệu lực",
        "",
        "🚫 KHIẾU NẠI:",
        "  • Khiếu nại sai sự thật, dựng chuyện để hãm hại người khác: xử lý ban tối thiểu 7 ngày",
        "  • Không chấp nhận lý do cho mượn acc khi bị xử lý",
        "",
        ""
      ],
      "lineCount": 83
    },
    {
      "id": "tocao",
      "title": "Tố cáo & kháng cáo",
      "icon": "📸",
      "summary": "Quy định bằng chứng, tố cáo vi phạm, kháng cáo và cách gửi ticket hợp lệ.",
      "lines": [
        "",
        "📸 BẰNG CHỨNG TỐ CÁO & KHÁNG CÁO",
        "",
        "",
        "🔹 CHƯƠNG I: QUY ĐỊNH CHUNG 🔹",
        "",
        "",
        "📌 NGUYÊN TẮC XỬ LÝ:",
        "",
        "  • ADMIN CHỈ giải quyết khi có ĐẦY ĐỦ BẰNG CHỨNG",
        "  • Không có bằng chứng = Không xử lý",
        "  • Không chấp nhận tố cáo hoặc kháng cáo dạng 'tôi nói thật', 'mọi người đều biết', v.v.",
        "",
        "",
        "🔹 CHƯƠNG II: TỐ CÁO (BÁO CÁO VI PHẠM) 🔹",
        "",
        "",
        "✅ BẰNG CHỨNG HỢP LỆ KHI TỐ CÁO:",
        "",
        "  • Video ghi hình (không cắt ghép, có tên người vi phạm, có thời gian)",
        "  • Ảnh chụp màn hình chat công khai (có nội dung vi phạm)",
        "  • Chat log từ Discord (nếu vi phạm xảy ra trên Discord)",
        "",
        "",
        "📋 CÁC LOẠI BẰNG CHỨNG VÀ GIÁ TRỊ:",
        "",
        "  [1] Video ghi hình:",
        "    → Giá trị: CAO NHẤT",
        "    → Yêu cầu: Không cắt ghép, ghi rõ tên người vi phạm, hành vi, thời gian",
        "    → Được chấp nhận ngay mà không cần thêm bằng chứng khác",
        "",
        "  [2] Ảnh chụp màn hình chat:",
        "    → Giá trị: TRUNG BÌNH - CAO (tùy trường hợp)",
        "    → Yêu cầu: Ảnh rõ nét, có tên người chat, có nội dung, không bị chỉnh sửa",
        "",
        "  [3] Server log:",
        "    → Giá trị: CAO NHẤT (chính xác tuyệt đối)",
        "    → Do ADMIN khai thác trực tiếp",
        "",
        "  [4] Chat riêng tư (DM Discord / in-game DM):",
        "    → Giá trị: THẤP - TRUNG BÌNH",
        "    → Yêu cầu: Phải có video quay toàn màn hình (không phải ảnh chụp)",
        "    → Ảnh chụp DM dễ bị làm giả, ADMIN có quyền từ chối",
        "",
        "  [5] Tố giác bằng miệng (không bằng chứng):",
        "    → Giá trị: KHÔNG CÓ GIÁ TRỊ",
        "    → ADMIN có quyền từ chối xử lý ngay lập tức",
        "",
        "",
        "❌ CÁC TRƯỜNG HỢP TỐ CÁO KHÔNG HỢP LỆ:",
        "",
        "  • Không có ảnh/video/log",
        "  • Ảnh/video bị cắt ghép, chỉnh sửa nội dung",
        "  • Không rõ tên người vi phạm",
        "  • Không rõ thời gian xảy ra",
        "  • Báo cáo sau khi sự việc xảy ra quá 1 ngày",
        "  • Tố cáo dạng 'tôi nghe nói', 'bạn tôi bảo', 'ai đó nói lại'",
        "",
        "",
        "📝 CÁCH GỬI TỐ CÁO ĐÚNG CÁCH:",
        "",
        "  • Bước 1: Thu thập bằng chứng (video/ảnh)",
        "  • Bước 2: Ghi lại thời gian, tọa độ, tên người vi phạm",
        "  • Bước 3: Gửi qua Ticket Discord (kênh hỗ trợ)",
        "  • Bước 4: Chờ ADMIN phản hồi (trong vòng 24-48 giờ)",
        "",
        "",
        "🔹 CHƯƠNG III: KHÁNG CÁO (KHI BỊ BAN OAN) 🔹",
        "",
        "",
        "✅ BẰNG CHỨNG HỢP LỆ KHI KHÁNG CÁO:",
        "  (Ví dụ - Chỉ để tham khảo)",
        "  • Video quay toàn màn hình từ lúc mở máy đến lúc vào server",
        "  • Ảnh chụp thư mục .minecraft/mods (chứng minh không cài hack)",
        "  • Log chứng minh bạn không online vào thời điểm vi phạm",
        "  • Bằng chứng về việc tài khoản bị hack (nếu có)",
        "  • Nhân chứng có uy tín (có thể được ADMIN xem xét)",
        "",
        "",
        "📋 CÁC CƠ SỞ ĐỂ ADMIN XEM XÉT KHÁNG CÁO:",
        "",
        "  • Bạn đưa ra được bằng chứng rõ ràng, không thể chối cãi",
        "  • Bạn chủ động báo ADMIN ngay khi phát hiện vấn đề",
        "  • Có sự nhầm lẫn từ phía ADMIN",
        "  • Tài khoản của bạn bị hack và bạn báo ngay lập tức",
        "  • Bạn bị ban do dùng chung IP nhưng chứng minh được không liên quan",
        "",
        "",
        "❌ CÁC TRƯỜNG HỢP KHÁNG CÁO KHÔNG HỢP LỆ:",
        "",
        "  • 'Tôi không làm' nhưng không có bằng chứng",
        "  • 'Tôi không biết luật' - Không chấp nhận",
        "  • 'Bạn tôi mượn acc' - Bạn vẫn chịu trách nhiệm",
        "  • 'Tôi bị hack' nhưng không báo ADMIN kịp thời",
        "  • Kháng cáo sau khi bị ban quá 1 ngày",
        "",
        "",
        "📝 CÁCH GỬI KHÁNG CÁO ĐÚNG CÁCH:",
        "",
        "  • Bước 1: Đọc kỹ lý do bị ban (ADMIN đã ghi khi ban)",
        "  • Bước 2: Thu thập bằng chứng chứng minh bạn vô tội",
        "  • Bước 3: Gửi qua Ticket Discord với tiêu đề 'KHÁNG CÁO - [TÊN TÀI KHOẢN]'",
        "  • Bước 4: Trình bày rõ ràng, cung cấp đầy đủ bằng chứng",
        "  • Bước 5: Chờ ADMIN xem xét (có thể mất 2-3 ngày)",
        "",
        "",
        "🔹 CHƯƠNG IV: QUY ĐỊNH CHUNG VỀ BẰNG CHỨNG 🔹",
        "",
        "",
        "⚠️ NHỮNG ĐIỀU CẦN LƯU Ý:",
        "",
        "  • ADMIN có quyền yêu cầu cung cấp thêm bằng chứng nếu thấy chưa đủ",
        "  • ADMIN có quyền từ chối xử lý nếu bằng chứng không rõ ràng",
        "  • Không được tự ý chỉnh sửa, cắt ghép ảnh/video (sẽ bị xử lý báo cáo sai)",
        "  • Báo cáo sai sự thật, dựng chuyện → xử lý ban tối thiểu 7 ngày",
        "",
        "",
        "👥 ĐỐI TƯỢNG ÁP DỤNG:",
        "  • Tất cả người chơi trên máy chủ",
        "  • Áp dụng cho mọi tài khoản liên quan (Alt Account)",
        "  • Áp dụng cho TẤT CẢ tài khoản có cùng IP",
        "",
        "",
        "📅 HIỆU LỰC THI HÀNH:",
        "  • Quy định có hiệu lực từ ngày công bố chính thức",
        "",
        "✏️ SỬA ĐỔI, BỔ SUNG:",
        "  • Đội Ngũ ADMIN có quyền sửa đổi khi cần thiết",
        "  • Thông báo công khai ít nhất 24 giờ trước khi có hiệu lực",
        ""
      ],
      "lineCount": 82
    },
    {
      "id": "ten",
      "title": "Đặt tên in-game & Discord",
      "icon": "🏷️",
      "summary": "Quy định tên, nickname, mạo danh, quảng cáo và cưỡng ép đổi tên.",
      "lines": [
        "",
        "🏷️ ĐẶT TÊN (IN-GAME & DISCORD)",
        "",
        "",
        "🔹 CHƯƠNG I: QUY ĐỊNH CHUNG 🔹",
        "",
        "",
        "📌 NGUYÊN TẮC CHUNG:",
        "",
        "  • Tên in-game (IGN), biệt danh (nickname), tên Discord phải LỊCH SỰ và PHÙ HỢP",
        "  • Không được sử dụng tên gây khó chịu, xúc phạm hoặc vi phạm thuần phong mỹ tục",
        "  • ADMIN có quyền yêu cầu đổi tên hoặc xử phạt nếu tên vi phạm",
        "  • Quy định này áp dụng cho CẢ IN-GAME và DISCORD",
        "",
        "",
        "🔹 CHƯƠNG II: CÁC TRƯỜNG HỢP TÊN BỊ CẤM 🔹",
        "",
        "",
        "❌ TÊN CÓ NỘI DUNG XÚC PHẠM:",
        "  • Chửi thề, thô tục, bạo lực (tiếng Việt, Anh hoặc bất kỳ ngôn ngữ nào)",
        "  • Phân biệt chủng tộc, tôn giáo, giới tính, vùng miền",
        "  • Nội dung chính trị nhạy cảm, lật đổ, chống phá",
        "  • Nội dung 18+, khiêu dâm, kinh dị",
        "",
        "❌ TÊN MẠO DANH:",
        "  • Giả mạo ADMIN, Mod, Staff (Owner, Admin, Mod, Shvn, ...)",
        "  • Giả mạo người chơi khác để gây nhầm lẫn, lừa đảo",
        "  • Tên giống bot hoặc hệ thống (Discord, Clyde, AutoMod, ...)",
        "",
        "❌ TÊN QUẢNG CÁO & LỪA ĐẢO:",
        "  • Quảng bá server khác, website, dịch vụ bên thứ ba",
        "  • Chứa link, URL, mã độc, lừa đảo",
        "",
        "❌ TÊN GÂY KHÓ CHỊU:",
        "  • Ký tự đặc biệt quá mức gây khó đọc, lỗi font",
        "  • Tên dài quá mức (≥10 ký tự) gây spam",
        "",
        "",
        "✅ TÊN ĐƯỢC CHẤP NHẬN:",
        "",
        "  • Tên bình thường, lịch sự (ví dụ: Minato, John, Alex)",
        "  • Tên có emoji hợp lý (không spam, không phản cảm)",
        "  • Tên trùng với IGN để dễ nhận diện (khuyến khích)",
        "",
        "",
        "🔹 CHƯƠNG III: HÌNH THỨC XỬ LÝ 🔹",
        "",
        "",
        "📊 KHUNG XỬ PHẠT:",
        "",
        "  • LẦN 1 (vi phạm nhẹ):",
        "    → Cảnh báo + CƯỠNG ÉP đổi tên trong vòng 24 giờ",
        "",
        "  • LẦN 2 (tái phạm):",
        "    → CƯỠNG ÉP đổi tên trong vòng 12 giờ",
        "    → Ban 3 ngày (cả in-game và Discord)",
        "",
        "  • LẦN 3 (tái phạm nhiều lần hoặc cố tình chống đối):",
        "    → BAN VĨNH VIỄN TOÀN BỘ TÀI KHOẢN (cả in-game và Discord)",
        "    → Không chấp nhận bất kỳ lý do hay khiếu nại nào",
        "",
        "",
        "⚠️ ĐẶC BIỆT - CHỐNG ĐỐI CƯỠNG ÉP ĐỔI TÊN:",
        "",
        "  • Cố tình đổi lại tên cũ hoặc tên vi phạm sau khi đã bị yêu cầu đổi:",
        "    → BAN VĨNH VIỄN NGAY LẬP TỨC",
        "    → Không cảnh báo – Không giảm án – Không unban",
        "",
        "  • Sử dụng alt account để tiếp tục chơi với tên vi phạm:",
        "    → Ban vĩnh viễn toàn bộ IP và các tài khoản liên quan.",
        "",
        "",
        "❌ CÁC HÀNH VI ĐƯỢC XEM LÀ CHỐNG ĐỐI:",
        "",
        "  • Đổi lại tên cũ sau khi đã bị yêu cầu đổi",
        "  • Đổi thành tên vi phạm khác (vẫn trong danh sách cấm)",
        "  • Từ chối đổi tên mặc dù đã được cảnh báo nhiều lần",
        "  • Lăng mạ, chửi bới ADMIN khi bị yêu cầu đổi tên",
        "  • Dùng alt account để tiếp tục chơi với tên vi phạm",
        "",
        "",
        "🔹 CHƯƠNG IV: TRÁCH NHIỆM CỦA NGƯỜI CHƠI 🔹",
        "",
        "",
        "📋 TRƯỚC KHI THAM GIA:",
        "",
        "  • Đảm bảo tên in-game và tên Discord KHÔNG vi phạm các điều cấm",
        "  • Nếu đang dùng tên vi phạm, hãy đổi NGAY trước khi bị xử lý",
        "",
        "",
        "📋 KHI BỊ YÊU CẦU ĐỔI TÊN:",
        "",
        "  • Phải thực hiện NGAY trong vòng 24 giờ",
        "  • Báo ADMIN sau khi đã đổi để xác nhận",
        "  • Không được dùng tên tương tự để 'lách luật'",
        "",
        "",
        "👥 ĐỐI TƯỢNG ÁP DỤNG:",
        "  • Tất cả người chơi trên máy chủ",
        "  • Tất cả thành viên trong Discord server",
        "  • Áp dụng cho mọi tài khoản liên quan (Alt Account)",
        "",
        "",
        "🔹 CHƯƠNG V: ĐIỀU KHOẢN THI HÀNH 🔹",
        "",
        "",
        "📅 HIỆU LỰC THI HÀNH:",
        "  • Quy định có hiệu lực từ ngày công bố chính thức",
        "",
        "✏️ SỬA ĐỔI, BỔ SUNG:",
        "  • Đội Ngũ ADMIN có quyền sửa đổi khi cần thiết",
        "  • Thông báo công khai ít nhất 24 giờ trước khi có hiệu lực",
        "",
        "🚫 KHIẾU NẠI:",
        "  • Tên vi phạm rõ ràng → Không chấp nhận khiếu nại",
        "  • Nếu bị nhầm, gửi ticket kèm bằng chứng",
        ""
      ],
      "lineCount": 70
    }
  ],
  "totalCategories": 15,
  "totalLines": 1370
};
